/**
 * Seven Sister States Regional Language Translation Service
 * Supports 11 North Eastern & Regional Languages with 100% Comprehensive Coverage:
 * English, Hindi, Assamese, Bengali, Khasi, Garo, Manipuri, Mizo, Nagamese, Kokborok, Nepali
 */

export type LanguageCode =
  | 'en' // English
  | 'hi' // Hindi (हिन्दी)
  | 'as' // Assamese (অসমীয়া)
  | 'bn' // Bengali (বাংলা)
  | 'kha' // Khasi (Ka Ktien Khasi)
  | 'gar' // Garo (A·chik)
  | 'mni' // Manipuri / Meitei (ꯃꯩꯇꯩꯂꯣꯟ)
  | 'mzo' // Mizo (Mizo ṭawng)
  | 'nag' // Nagamese (Nagaland)
  | 'kok' // Kokborok (Tripura)
  | 'ne'; // Nepali (नेपाली)

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  region: string;
  flag: string;
  locale: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'Global / Standard', flag: '🇬🇧', locale: 'en-US' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'Common Regional', flag: '🇮🇳', locale: 'hi-IN' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam', flag: '🌾', locale: 'as-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'Tripura / Assam', flag: '🇧🇩', locale: 'bn-IN' },
  { code: 'kha', name: 'Khasi', nativeName: 'Ka Ktien Khasi', region: 'Meghalaya', flag: '⛰️', locale: 'en-IN' },
  { code: 'gar', name: 'Garo', nativeName: 'A·chik', region: 'Meghalaya', flag: '🌿', locale: 'en-IN' },
  { code: 'mni', name: 'Manipuri', nativeName: 'ꯃꯩꯇꯩꯂꯣꯟ', region: 'Manipur', flag: '🏹', locale: 'en-IN' },
  { code: 'mzo', name: 'Mizo', nativeName: 'Mizo ṭawng', region: 'Mizoram', flag: '🏞️', locale: 'en-IN' },
  { code: 'nag', name: 'Nagamese', nativeName: 'Nagamese', region: 'Nagaland', flag: '🏔️', locale: 'en-IN' },
  { code: 'kok', name: 'Kokborok', nativeName: 'Kokborok', region: 'Tripura', flag: '🗣️', locale: 'en-IN' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', region: 'Sikkim', flag: '🏔️', locale: 'ne-NP' },
];

export interface TranslationDictionary {
  appTitle: string;
  appSubtitle: string;
  dashboard: string;
  alerts: string;
  report: string;
  sensors: string;
  settings: string;
  sosEmergency: string;
  signIn: string;
  signOut: string;
  emergencyContacts: string;
  voiceMicTooltip: string;
  listeningVoice: string;
  redAlert: string;
  evacuateNow: string;
  readOfficialBulletin: string;
  broadcastSMS: string;
  helplines: string;
  shelters: string;
  voiceAssistantTitle: string;
  voiceAssistantSub: string;
  quickCommandsTitle: string;
  cmdSosTitle: string;
  cmdSosDesc: string;
  cmdSheltersTitle: string;
  cmdSheltersDesc: string;
  cmdWeatherTitle: string;
  cmdWeatherDesc: string;
  cmdRoadTitle: string;
  cmdRoadDesc: string;
  cmdHelplinesTitle: string;
  cmdHelplinesDesc: string;
  cmdMedicalTitle: string;
  cmdMedicalDesc: string;
  responseSos: string;
  responseShelters: string;
  responseWeather: string;
  responseRoad: string;
  responseHelplines: string;
  responseMedical: string;
  replayAudio: string;
  typeQuestionPlaceholder: string;
  aiSpokenResponse: string;

  // Comprehensive Dashboard & Map Translations
  highRiskCorridors: string;
  blockedStatus: string;
  vulnerableStatus: string;
  clearStatus: string;
  spatialGisRadar: string;
  liveTerrainSatellite: string;
  allLayers: string;
  supplyVehicles: string;
  highwayCorridors: string;
  vulnerableRoadZones: string;
  topoBasemap: string;
  satelliteBasemap: string;
  legendTitle: string;
  legendConvoy: string;
  legendBlocked: string;
  legendHighRisk: string;
  legendClearPass: string;
  logisticsTitle: string;
  logisticsSub: string;
  activeConvoysCard: string;
  criticalBlockagesCard: string;
  passableRoutesCard: string;
  reRouteAdviceTitle: string;
  divertConvoysBtn: string;

  // Logistics Tabs & Features
  tabConvoyFleet: string;
  tabAiRouting: string;
  tabIsolatedVillages: string;
  tabIvrAlerts: string;
  liveGpsText: string;
  approxDistrictText: string;
  tapToChangeMode: string;
  simulateLandslide: string;
  resetSimulation: string;
  searchConvoyPlaceholder: string;

  // Other screen titles and items
  alertsTitle: string;
  alertsSub: string;
  controlRoomsTitle: string;
  callEmergency: string;
  activeWarningsTitle: string;
  reportTitle: string;
  reportSub: string;
  reportType: string;
  submitReportBtn: string;
  uploadPhoto: string;
  locationGeotag: string;
  description: string;
  sensorsTitle: string;
  sensorsSub: string;
  soilMoisture: string;
  rainfallGauge: string;
  tiltAngle: string;
  porePressure: string;
  liveStatus: string;
  settingsTitle: string;
  settingsSub: string;
  languageLabel: string;
  themeLabel: string;
  notificationsLabel: string;
  userProfile: string;
}

export const TRANSLATIONS: Record<LanguageCode, TranslationDictionary> = {
  en: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Smart Logistics & Accessibility Grid',
    dashboard: 'Dashboard',
    alerts: 'Alerts',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS EMERGENCY',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Emergency Contacts (Friends & Family)',
    voiceMicTooltip: 'LOGIX AI Voice Assistant',
    listeningVoice: 'Listening for regional commands...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'EVACUATE IMMEDIATELY',
    readOfficialBulletin: 'Read Official Bulletin',
    broadcastSMS: 'Broadcast via SMS 📱',
    helplines: 'Emergency Hotlines',
    shelters: 'Relief Camps & Shelters',
    voiceAssistantTitle: 'LOGIX AI Voice Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Nearest Safe Camps',
    cmdWeatherTitle: 'Monsoon Weather',
    cmdWeatherDesc: 'Rainfall & Saturation',
    cmdRoadTitle: 'Road & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helplines',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency Distress Detected! Siren activated & GPS SOS dispatched to NDRF 1078.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Supplies active.',
    responseWeather: '🌧️ Weather Advisory: Heavy monsoon downpour continuing across Meghalaya & Sikkim. Slope saturation 87%.',
    responseRoad: '🛣️ Route Advisory: NH-10 Teesta Bazaar is blocked. Emergency traffic diverted via Lava pass.',
    responseHelplines: '📞 Emergency Hotlines: National 112, NDRF 1078, State Disaster Operation 1070.',
    responseMedical: '🚑 Medical Convoy Alert: Essential medicine & ration supplies cleared through Lava-Algarah bypass.',
    replayAudio: '🔊 Replay Audio',
    typeQuestionPlaceholder: 'Type a question (e.g. Shelters, Weather, NH-10)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'High-Risk Highway Corridors',
    blockedStatus: 'BLOCKED',
    vulnerableStatus: 'VULNERABLE',
    clearStatus: 'CLEAR',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'All Layers',
    supplyVehicles: 'Supply Vehicles',
    highwayCorridors: 'Highway Corridors',
    vulnerableRoadZones: 'Vulnerable Road Zones',
    topoBasemap: 'Topo',
    satelliteBasemap: 'Satellite',
    legendTitle: 'LEGEND',
    legendConvoy: '🚚 Convoy',
    legendBlocked: '🔴 Blocked',
    legendHighRisk: '🟡 High Risk',
    legendClearPass: '🟢 Clear Pass',
    logisticsTitle: 'AI Dynamic Route Optimization & Convoy Tracker',
    logisticsSub: 'Real-Time Telemetry & Disruption Bypass Router',
    activeConvoysCard: 'Active Convoys in Transit',
    criticalBlockagesCard: 'Critical Road Blockages',
    passableRoutesCard: 'Clear Mountain Corridors',
    reRouteAdviceTitle: 'AI RE-ROUTE RECOMMENDATION',
    divertConvoysBtn: 'Divert Convoys',
    tabConvoyFleet: '1. Convoy Fleet',
    tabAiRouting: '2. AI Graph Routing',
    tabIsolatedVillages: '3. Isolated Villages',
    tabIvrAlerts: '4. IVR & Alerts',
    liveGpsText: 'Live GPS',
    approxDistrictText: 'Approx. District',
    tapToChangeMode: 'Tap to change mode',
    simulateLandslide: 'Simulate Landslide ➔ Trigger Reroute',
    resetSimulation: 'Reset Simulation',
    searchConvoyPlaceholder: 'Search convoy by cargo, vehicle no, route...',
    alertsTitle: 'Disaster Early Warnings & Control Rooms',
    alertsSub: '24/7 Real-Time Emergency Logistics Hotlines',
    controlRoomsTitle: 'Emergency Control Room Hotlines',
    callEmergency: 'Call Hotline',
    activeWarningsTitle: 'Active Early Warnings',
    reportTitle: 'Citizen & Field Incident Report',
    reportSub: 'Submit live landslide, road damage or blockade',
    reportType: 'Incident Type',
    submitReportBtn: 'Submit Live Incident Report',
    uploadPhoto: 'Upload Field Photos',
    locationGeotag: 'GPS Geotag Location',
    description: 'Detailed Description',
    sensorsTitle: 'IoT Telemetry & Slope Stability Sensors',
    sensorsSub: 'Real-time geotechnical sensor grid data',
    soilMoisture: 'Soil Moisture',
    rainfallGauge: 'Rainfall Gauge',
    tiltAngle: 'Slope Tilt Angle',
    porePressure: 'Pore Water Pressure',
    liveStatus: 'Live Status',
    settingsTitle: 'System Settings & Regional Preferences',
    settingsSub: 'Configure language, map layers, theme and contacts',
    languageLabel: 'Select Interface Language',
    themeLabel: 'App Theme',
    notificationsLabel: 'Emergency Notifications',
    userProfile: 'User Profile & Role',
  },
  nag: {
    appTitle: 'লজিক্স-এনইআৰ',
    appSubtitle: 'এআই রাস্তা আরু সাপ্লাই গাড়ি ট্র্যাকার',
    dashboard: 'ड्यासबोर्ड',
    alerts: 'सब् चेतावनी',
    report: 'खतरा रिपोर्ट',
    sensors: 'सेन्सर डाटा',
    settings: 'सेटिङ्',
    sosEmergency: 'खतरा एसओएस',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    emergencyContacts: 'घर मानु आरु साथी खबोर',
    voiceMicTooltip: 'LOGIX AI सहायक',
    listeningVoice: 'आवाज आदेश सुनि आसे...',
    redAlert: 'रेड अलर्ट - स्तर ४',
    evacuateNow: 'जल्दी सेफ जागात जाबी',
    readOfficialBulletin: 'सरकारी खबोर पढीबी',
    broadcastSMS: 'एसएमएस पठाईबी 📱',
    helplines: 'इमर्जेन्सी नम्बर',
    shelters: 'राहत क्याम्प',
    voiceAssistantTitle: 'LOGIX AI भ्वाइस सहायक',
    voiceAssistantSub: 'नागाल्याण्ड आरु उत्तर-पूर्व ग्रिड',
    quickCommandsTitle: 'सब्से जरूरी कमान्ड्स:',
    cmdSosTitle: 'खतरा एसओएस',
    cmdSosDesc: 'साइरन आरु जीपीएस म्यासेज',
    cmdSheltersTitle: 'राहत क्याम्प',
    cmdSheltersDesc: 'काखते सेफ क्याम्प',
    cmdWeatherTitle: 'बरफ आरु पानी मौसम',
    cmdWeatherDesc: 'बरखा आरु माटी खहा',
    cmdRoadTitle: 'रास्ता आरु बाइपास',
    cmdRoadDesc: 'एनएच-२९ आरु एनएच-१०',
    cmdHelplinesTitle: 'हेल्पलाइन नम्बर',
    cmdHelplinesDesc: 'एनडीआरएफ १०७८ आरु ११२',
    cmdMedicalTitle: 'दवाई गाड़ी कन्भोय',
    cmdMedicalDesc: 'जरूरी दवाई आरु राशन',
    responseSos: '🚨 खतरा संकेत पाइसे! साइरन बाजीसे आरु एनडीआरएफ १०७८ ते जीपीएस लोकेशन पठाइ दीसे।',
    responseShelters: '🏠 काखते राहत क्याम्प: जेएन स्टेडियम पोलो ग्राउन्ड (३४०/१२०० क्षमता)। खाना आरु दवाई सब आसे।',
    responseWeather: '🌧️ मौसम खबोर: नागाल्याण्ड आरु मेघालय ते भारी बरखा हुइ आसे। माटी खहा रिस्क ८७% आसे।',
    responseRoad: '🛣️ रास्ता खबोर: एनएच-१० तीस्ता बजार बन्द आसे। सब गाड़िखान लाभा बाइपास रास्ता से जाइ आसे।',
    responseHelplines: '📞 इमर्जेन्सी हेल्पलाइन: राष्ट्रिय ११२, एनडीआरएफ १०७८, स्टेट डिसास्टर १०७०।',
    responseMedical: '🚑 दवाई गाड़ी: जरूरी दवाई आरु राशन गाड़ी लाभा बाइपास से सेफ-ते पार हुइ आसे।',
    replayAudio: '🔊 आवाज फेर सुनिबी',
    typeQuestionPlaceholder: 'सवाल लिखिबी (राहत क्याम्प, रास्ता, मौसम)...',
    aiSpokenResponse: 'एआई आवाज जवाफ',
    highRiskCorridors: 'खतरा हाइवे रास्ता',
    blockedStatus: 'बन्द आसे',
    vulnerableStatus: 'खतरा आसे',
    clearStatus: 'साफ आसे',
    spatialGisRadar: 'एनईआर म्याप रडार',
    liveTerrainSatellite: 'लाइभ म्याप आरु सेटेलाइट',
    allLayers: 'सब लेयर्स',
    supplyVehicles: 'सप्लाई गाड़िखान',
    highwayCorridors: 'हाइवे रास्ता',
    vulnerableRoadZones: 'खतरा रोड एरिया',
    topoBasemap: 'टोपो',
    satelliteBasemap: 'सेटेलाइट',
    legendTitle: 'म्याप सूचक',
    legendConvoy: '🚚 सप्लाई गाड़ी',
    legendBlocked: '🔴 बन्द रास्ता',
    legendHighRisk: '🟡 खतरा रास्ता',
    legendClearPass: '🟢 खुला रास्ता',
    logisticsTitle: 'एआई रास्ता ट्र्याकर आरु गाड़ी मोनिटर',
    logisticsSub: 'लाइभ जीपीएस आरु बाइपास रास्ता इन्जिन',
    activeConvoysCard: 'चलि थका सप्लाई गाड़िखान',
    criticalBlockagesCard: 'बन्द हुवा रास्ता',
    passableRoutesCard: 'खुला पहाड़ी रास्ता',
    reRouteAdviceTitle: 'एआई रास्ता बदल सल्लाह',
    divertConvoysBtn: 'गाड़ी बदलिबी',
    tabConvoyFleet: '१. सप्लाई गाड़िखान',
    tabAiRouting: '२. एआई रास्ता नेभिगेसन',
    tabIsolatedVillages: '३. फँसी थका गाउँ',
    tabIvrAlerts: '४. आइभिआर आरु फोन कल',
    liveGpsText: 'लाइभ जीपीएस',
    approxDistrictText: 'जिल्ला लोकेशन',
    tapToChangeMode: 'लोकेशन मोड बदलिबी',
    simulateLandslide: 'पहिरो डेमो सुरू करिबी',
    resetSimulation: 'डेमो रिसेट करिबी',
    searchConvoyPlaceholder: 'गाड़ी नम्बर वा सामान खोजिबी...',
    alertsTitle: 'आपत्कालीन चेतावनी आरु कन्ट्रोल रुम',
    alertsSub: 'उत्तर-पूर्व २४/७ इमर्जेन्सी सहायता',
    controlRoomsTitle: '२४/७ कन्ट्रोल रुम हेल्पलाइन',
    callEmergency: 'कल करिबी',
    activeWarningsTitle: 'सक्रिय चेतावनीहरू',
    reportTitle: 'पहिरो खतरा रिपोर्ट',
    reportSub: 'नागरिक आरु फिल्ड रिपोर्टिङ',
    reportType: 'घटना प्रकार',
    submitReportBtn: 'रिपोर्ट पठाउबी',
    uploadPhoto: 'फोटो हालिबी',
    locationGeotag: 'जीपीएस लोकेशन',
    description: 'विवरण लिखिबी',
    sensorsTitle: 'आईओटी सेन्सर डाटा',
    sensorsSub: 'माटी आरु पहिरो मोनिटरिङ',
    soilMoisture: 'माटीको आर्द्रता',
    rainfallGauge: 'बरखा मिटर',
    tiltAngle: 'ढलान कोण',
    porePressure: 'पानीको चाप',
    liveStatus: 'लाइभ स्थिति',
    settingsTitle: 'एप सेटिङ्',
    settingsSub: 'भाषा, थीम आरु सुरक्षा',
    languageLabel: 'भाषा छानिबी',
    themeLabel: 'थीम',
    notificationsLabel: 'सूचना',
    userProfile: 'प्रयोगकर्ता प्रोफाइल',
  },
  hi: {
    appTitle: 'लॉजिक्स-एनईआर',
    appSubtitle: 'एआई स्मार्ट लॉजिस्टिक्स एवं मार्ग ग्रिड',
    dashboard: 'डैशबोर्ड',
    alerts: 'चेतावनी',
    report: 'रिपोर्ट दर्ज करें',
    sensors: 'सेंसर डेटा',
    settings: 'सेटिंग्स',
    sosEmergency: 'आपातकालीन एसओएस',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट',
    emergencyContacts: 'आपातकालीन संपर्क (परिवार और मित्र)',
    voiceMicTooltip: 'लॉजिक्स एआई सहायक',
    listeningVoice: 'क्षेत्रीय आवाज कमांड सुन रहा है...',
    redAlert: 'रेड अलर्ट - स्तर 4',
    evacuateNow: 'तुरंत सुरक्षित स्थान पर जाएं',
    readOfficialBulletin: 'आधिकारिक बुलेटिन पढ़ें',
    broadcastSMS: 'एसएमएस से भेजें 📱',
    helplines: 'आपातकालीन हेल्पलाइन',
    shelters: 'राहत शिविर',
    voiceAssistantTitle: 'लॉजिक्स एआई वॉयस सहायक',
    voiceAssistantSub: 'उत्तर-पूर्व क्षेत्रीय ग्रिड',
    quickCommandsTitle: 'त्वरित वॉयस कमांड:',
    cmdSosTitle: 'आपातकालीन एसओएस',
    cmdSosDesc: 'सायरन + जीपीएस संदेश',
    cmdSheltersTitle: 'राहत शिविर',
    cmdSheltersDesc: 'निकटतम सुरक्षित शिविर',
    cmdWeatherTitle: 'मानसून मौसम',
    cmdWeatherDesc: 'बारिश और मिट्टी नमी',
    cmdRoadTitle: 'सड़क एवं बाईपास',
    cmdRoadDesc: 'एनएच-10 लावा मार्ग',
    cmdHelplinesTitle: 'हेल्पलाइन नंबर',
    cmdHelplinesDesc: 'एनडीआरएफ 1078 और 112',
    cmdMedicalTitle: 'चिकित्सा आपूर्ति',
    cmdMedicalDesc: 'आवश्यक राहत सामग्री',
    responseSos: '🚨 आपातकालीन खतरा दर्ज हुआ! सायरन सक्रिय और एनडीआरएफ 1078 को जीपीएस संदेश भेजा गया।',
    responseShelters: '🏠 निकटतम राहत शिविर: जेएन स्टेडियम पोलो ग्राउंड्स (340/1200 क्षमता)। खाद्य सामग्री उपलब्ध है।',
    responseWeather: '🌧️ मौसम सलाह: मेघालय और सिक्किम में भारी मानसूनी बारिश जारी है। ढलान संतृप्ति 87% है।',
    responseRoad: '🛣️ मार्ग सलाह: एनएच-10 तीस्ता बाजार बंद है। आपातकालीन यातायात लावा बाईपास से निकाला जा रहा है।',
    responseHelplines: '📞 आपातकालीन हेल्पलाइन: राष्ट्रीय 112, एनडीआरएफ 1078, राज्य आपदा नियंत्रण 1070।',
    responseMedical: '🚑 चिकित्सा काफिला: आवश्यक दवाएं और राशन लावा-अलगरह मार्ग से सुरक्षित निकाले जा रहे हैं।',
    replayAudio: '🔊 फिर से सुनें',
    typeQuestionPlaceholder: 'सवाल लिखें (जैसे: राहत शिविर, मौसम, सड़क मार्ग)...',
    aiSpokenResponse: 'एआई वॉयस उत्तर',
    highRiskCorridors: 'उच्च जोखिम वाले राजमार्ग गलियारे',
    blockedStatus: 'अवरुद्ध',
    vulnerableStatus: 'संवेदनशील',
    clearStatus: 'खुला मार्ग',
    spatialGisRadar: 'एनईआर स्थानिक जीआईएस रडार',
    liveTerrainSatellite: 'लाइव भूभाग एवं उपग्रह मानचित्र',
    allLayers: 'सभी परतें',
    supplyVehicles: 'आपूर्ति वाहन',
    highwayCorridors: 'राजमार्ग गलियारे',
    vulnerableRoadZones: 'संवेदनशील सड़क क्षेत्र',
    topoBasemap: 'टोपो',
    satelliteBasemap: 'उपग्रह',
    legendTitle: 'संकेतक',
    legendConvoy: '🚚 आपूर्ति वाहन',
    legendBlocked: '🔴 अवरुद्ध मार्ग',
    legendHighRisk: '🟡 उच्च जोखिम',
    legendClearPass: '🟢 सुरक्षित मार्ग',
    logisticsTitle: 'एआई मार्ग अनुकूलन एवं काफिला ट्रैकर',
    logisticsSub: 'रीयल-टाइम जीपीएस एवं भूस्खलन बाईपास प्रणाली',
    activeConvoysCard: 'पारगमन में सक्रिय काफिले',
    criticalBlockagesCard: 'अवरुद्ध प्रमुख सड़कें',
    passableRoutesCard: 'खुले पर्वतीय गलियारे',
    reRouteAdviceTitle: 'एआई वैकल्पिक मार्ग अनुशंसा',
    divertConvoysBtn: 'काफिला मोड़ें',
    tabConvoyFleet: '1. आपूर्ति वाहन बेड़ा',
    tabAiRouting: '2. एआई नेविगेशन मार्ग',
    tabIsolatedVillages: '3. अलग-थलग गांव',
    tabIvrAlerts: '4. आईवीआर एवं फोन अलर्ट',
    liveGpsText: 'लाइव जीपीएस',
    approxDistrictText: 'अनुमानित जिला',
    tapToChangeMode: 'मोड बदलने हेतु स्पर्श करें',
    simulateLandslide: 'भूस्खलन सिमुलेशन ➔ मार्ग परिवर्तन',
    resetSimulation: 'सिमुलेशन रीसेट करें',
    searchConvoyPlaceholder: 'सामग्री, वाहन संख्या या मार्ग से खोजें...',
    alertsTitle: 'आपदा प्रारंभिक चेतावनी एवं नियंत्रण कक्ष',
    alertsSub: '24/7 रीयल-टाइम आपातकालीन हॉटलाइन',
    controlRoomsTitle: 'आपातकालीन नियंत्रण कक्ष हेल्पलाइन',
    callEmergency: 'कॉल करें',
    activeWarningsTitle: 'सक्रिय प्रारंभिक चेतावनी',
    reportTitle: 'नागरिक एवं फील्ड घटना रिपोर्ट',
    reportSub: 'भूस्खलन या सड़क क्षति की रिपोर्ट दर्ज करें',
    reportType: 'घटना का प्रकार',
    submitReportBtn: 'रिपोर्ट सबमिट करें',
    uploadPhoto: 'तस्वीर अपलोड करें',
    locationGeotag: 'जीपीएस लोकेशन',
    description: 'विस्तृत विवरण',
    sensorsTitle: 'आईओटी सेंसर एवं ढलान स्थिरता',
    sensorsSub: 'रीयल-टाइम भू-तकनीकी सेंसर ग्रिड डेटा',
    soilMoisture: 'मिट्टी की नमी',
    rainfallGauge: 'वर्षा मापक',
    tiltAngle: 'झुकाव कोण',
    porePressure: 'छिद्र जल दबाव',
    liveStatus: 'लाइव स्थिति',
    settingsTitle: 'सिस्टम सेटिंग्स एवं क्षेत्रीय प्राथमिकताएं',
    settingsSub: 'भाषा, मानचित्र परतें और संपर्क प्रबंधित करें',
    languageLabel: 'इंटरफ़ेस भाषा चुनें',
    themeLabel: 'ऐप थीम',
    notificationsLabel: 'आपातकालीन सूचनाएं',
    userProfile: 'उपयोगकर्ता प्रोफ़ाइल',
  },
  as: {
    appTitle: 'লজিক্স-এনইআৰ',
    appSubtitle: 'এআই স্মাৰ্ট লজিষ্টিকছ আৰু পথ সুগমতা গ্ৰিড',
    dashboard: 'ডেশ্ববৰ্ড',
    alerts: 'সতৰ্কবাৰ্তা',
    report: 'ৰিপৰ্ট',
    sensors: 'চেনচৰ',
    settings: 'চেটিংছ',
    sosEmergency: 'জৰুৰীকালীন এছ.অ.এছ',
    signIn: 'চাইন ইন',
    signOut: 'চাইন আউট',
    emergencyContacts: 'জৰুৰীকালীন যোগাযোগ (পৰিয়াল আৰু বন্ধু)',
    voiceMicTooltip: 'লজিক্স এআই সহায়ক',
    listeningVoice: 'কণ্ঠ নিৰ্দেশনা শুনি আছে...',
    redAlert: 'ৰেড এলাৰ্ট - স্তৰ ৪',
    evacuateNow: 'তাত্ক্ষণিক স্থানান্তৰ হওক',
    readOfficialBulletin: 'চৰকাৰী জাননী পঢ়ক',
    broadcastSMS: 'এছ.এম.এছ প্ৰেৰণ 📱',
    helplines: 'জৰুৰীকালীন হেল্পলাইন',
    shelters: 'আশ্ৰয় শিবিৰ',
    voiceAssistantTitle: 'লজিক্স এআই কণ্ঠ সহায়ক',
    voiceAssistantSub: 'উত্তৰ-পূৰ্বাঞ্চল আঞ্চলিক গ্ৰিড',
    quickCommandsTitle: 'দ্ৰুত কণ্ঠ নিৰ্দেশনা:',
    cmdSosTitle: 'জৰুৰী এছ.অ.এছ',
    cmdSosDesc: 'ছাইৰেন + জিপিএছ বাৰ্তা',
    cmdSheltersTitle: 'আশ্ৰয় শিবিৰ',
    cmdSheltersDesc: 'ওচৰৰ সুৰক্ষিত শিবিৰ',
    cmdWeatherTitle: 'বৰষুণৰ বতৰ',
    cmdWeatherDesc: 'বৃষ্টিপাত আৰু মাটিৰ আৰ্দ্ৰতা',
    cmdRoadTitle: 'পথ আৰু বাইপাছ',
    cmdRoadDesc: 'এনএইচ-১০ লাভা ডাইভাৰ্চন',
    cmdHelplinesTitle: 'হেল্পলাইন নম্বৰ',
    cmdHelplinesDesc: 'এনডিআৰএফ ১০৭৮ আৰু ১১২',
    cmdMedicalTitle: 'চিকিৎসা কনভয়',
    cmdMedicalDesc: 'অত্যাৱশ্যকীয় যোগান',
    responseSos: '🚨 জৰুৰী বিপদ সংকেত চিনাক্ত! ছাইৰেন বাজিল আৰু এনডিআৰএফ ১০৭৮ লৈ এছ.অ.এছ বাৰ্তা প্ৰেৰণ কৰা হ’ল।',
    responseShelters: '🏠 ওচৰৰ আশ্ৰয় শিবিৰ: জেএন ষ্টেডিয়াম পোল’ গ্ৰাউণ্ড (৩৪০/১২০০ ক্ষমতা)। সাহায্য সক্ৰিয়।',
    responseWeather: '🌧️ বতৰৰ সতৰ্কবাৰ্তা: মেঘালয় আৰু ছিকিমত প্ৰবল বৰষুণ অব্যাহত। ভূমিস্খলনৰ সম্ভাৱনা ৮৭%।',
    responseRoad: '🛣️ পথ জাননী: এনএইচ-১০ তিস্তা বজাৰ বন্ধ। জৰুৰী যাতায়াত লাভা বাইপাছেৰে নিয়ন্ত্ৰিত।',
    responseHelplines: '📞 জৰুৰী হেল্পলাইন: ৰাষ্ট্ৰীয় ১১২, এনডিআৰএফ ১০৭৮, ৰাজ্যিক দুৰ্যোগ নিয়ন্ত্ৰণ ১০৭০।',
    responseMedical: '🚑 চিকিৎসা কনভয়: অত্যাৱশ্যকীয় ঔষধ আৰু খাদ্য লাভা পথৰ জৰিয়তে সুকলমে পঠিওৱা হৈছে।',
    replayAudio: '🔊 পুনৰ শুনক',
    typeQuestionPlaceholder: 'প্ৰশ্ন লিখক (যেনে: আশ্ৰয় শিবিৰ, বতৰ, পথ)...',
    aiSpokenResponse: 'এআই কণ্ঠ উত্তৰ',
    highRiskCorridors: 'উচ্চ সংকটপূৰ্ণ ঘাইপথসমূহ',
    blockedStatus: 'বন্ধ পথ',
    vulnerableStatus: 'সংকটপূৰ্ণ',
    clearStatus: 'মুকলি পথ',
    spatialGisRadar: 'উত্তৰ-পূব জিআইএছ ৰাডাৰ',
    liveTerrainSatellite: 'লাইভ ভূখণ্ড আৰু উপগ্ৰহ মানচিত্ৰ',
    allLayers: 'সকলো স্তৰ',
    supplyVehicles: 'যোগান বাহন',
    highwayCorridors: 'ঘাইপথসমূহ',
    vulnerableRoadZones: 'সংকটপূৰ্ণ অঞ্চল',
    topoBasemap: 'ভূখণ্ড',
    satelliteBasemap: 'উপগ্ৰহ',
    legendTitle: 'মানচিত্ৰ সূচক',
    legendConvoy: '🚚 যোগান কনভয়',
    legendBlocked: '🔴 বন্ধ পথ',
    legendHighRisk: '🟡 সংকটপূৰ্ণ',
    legendClearPass: '🟢 মুকলি বাট',
    logisticsTitle: 'এআই গতিশীল পথ নিৰ্ধাৰণ আৰু কনভয় ট্ৰেকাৰ',
    logisticsSub: 'প্ৰত্যক্ষ জিপিএছ আৰু বিকল্প পথ ব্যৱস্থাপনা',
    activeConvoysCard: 'চলি থকা সক্ৰিয় কনভয়',
    criticalBlockagesCard: 'বন্ধ হোৱা ঘাইপথসমূহ',
    passableRoutesCard: 'মুকলি পাহাৰীয়া বাট',
    reRouteAdviceTitle: 'এআই বিকল্প পথৰ পৰামৰ্শ',
    divertConvoysBtn: 'পথ সলনি কৰক',
    tabConvoyFleet: '১. যোগান বাহনসমূহ',
    tabAiRouting: '২. এআই পথ নিৰ্দেশনা',
    tabIsolatedVillages: '৩. বিচ্ছিন্ন গাঁওসমূহ',
    tabIvrAlerts: '৪. আইভিআৰ আৰু সতৰ্কবাৰ্তা',
    liveGpsText: 'লাইভ জিপিএছ',
    approxDistrictText: 'আনুমানিক জিলা',
    tapToChangeMode: 'মোড সলনি কৰিবলৈ স্পৰ্শ কৰক',
    simulateLandslide: 'ভূমিস্খলন অনুকৰণ ➔ পথ সলনি',
    resetSimulation: 'অনুকৰণ পুনৰাৰম্ভ কৰক',
    searchConvoyPlaceholder: 'সামগ্ৰী, গাড়ী নম্বৰ বা পথেৰে সন্ধান কৰক...',
    alertsTitle: 'দুৰ্যোগ প্ৰাৰম্ভিক সতৰ্কবাৰ্তা আৰু নিয়ন্ত্ৰণ কক্ষ',
    alertsSub: '২৪/৭ জৰুৰীকালীন সহায় হটলাইন',
    controlRoomsTitle: 'জৰুৰী নিয়ন্ত্ৰণ কক্ষ নম্বৰসমূহ',
    callEmergency: 'কল কৰক',
    activeWarningsTitle: 'সক্ৰিয় সতৰ্কবাৰ্তাসমূহ',
    reportTitle: 'নাগৰিক আৰু ফিল্ড ঘটনা ৰিপৰ্ট',
    reportSub: 'ভূমিস্খলন বা পথ ক্ষতিৰ ৰিপৰ্ট দাখিল কৰক',
    reportType: 'ঘটনাৰ প্ৰকাৰ',
    submitReportBtn: 'ৰিপৰ্ট দাখিল কৰক',
    uploadPhoto: 'ফটো আপলোড কৰক',
    locationGeotag: 'জিপিএছ অৱস্থান',
    description: 'বিস্তাৰিত বিৱৰণ',
    sensorsTitle: 'আইঅ’টি চেনচৰ আৰু পাহাৰ স্থিৰতা',
    sensorsSub: 'প্ৰত্যক্ষ ভূতাত্ত্বিক চেনচৰ তথ্য',
    soilMoisture: 'মাটিৰ আৰ্দ্ৰতা',
    rainfallGauge: 'বৃষ্টি মাপক',
    tiltAngle: 'হেলনীয়া কোণ',
    porePressure: 'জলীয় চাপ',
    liveStatus: 'প্ৰত্যক্ষ স্থিতি',
    settingsTitle: 'ব্যৱস্থাৰ চেটিংছ আৰু আঞ্চলিক পছন্দ',
    settingsSub: 'ভাষা, মানচিত্ৰ স্তৰ আৰু যোগাযোগ ব্যৱস্থাপনা',
    languageLabel: 'ভাষা নিৰ্বাচন কৰক',
    themeLabel: 'থিম',
    notificationsLabel: 'জৰুৰী জাননীসমূহ',
    userProfile: 'ব্যৱহাৰকাৰী প্ৰফাইল',
  },
  bn: {
    appTitle: 'লজিক্স-এনইআর',
    appSubtitle: 'এআই স্মার্ট লজিস্টিকস ও পথ গ্রিড',
    dashboard: 'ড্যাশবোর্ড',
    alerts: 'সতর্কবার্তা',
    report: 'রিপোর্ট',
    sensors: 'সেন্সর',
    settings: 'সেটিংস',
    sosEmergency: 'জরুরি এসওএস',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    emergencyContacts: 'জরুরি যোগাযোগ (পরিবার ও বন্ধু)',
    voiceMicTooltip: 'লজিক্স এআই সহায়ক',
    listeningVoice: 'ভয়েস কমান্ড শুনছে...',
    redAlert: 'রেড অ্যালার্ট - লেভেল ৪',
    evacuateNow: 'অবিলম্বে নিরাপদ স্থানে যান',
    readOfficialBulletin: 'সরকারী বুলেটিন পড়ুন',
    broadcastSMS: 'এসএমএস পাঠান 📱',
    helplines: 'জরুরি হেল্পলাইন',
    shelters: 'ত্রাণ শিবির',
    voiceAssistantTitle: 'লজিক্স এআই ভয়েস সহকারী',
    voiceAssistantSub: 'উত্তর-পূর্ব আঞ্চলিক গ্রিড',
    quickCommandsTitle: 'দ্রুত ভয়েস কমান্ড:',
    cmdSosTitle: 'জরুরি এসওএস',
    cmdSosDesc: 'সাইরেন + জিপিএস বার্তা',
    cmdSheltersTitle: 'ত্রাণ শিবির',
    cmdSheltersDesc: 'নিকটবর্তী নিরাপদ শিবির',
    cmdWeatherTitle: 'বর্ষার আবহাওয়া',
    cmdWeatherDesc: 'বৃষ্টিপাত ও মাটির আর্দ্রতা',
    cmdRoadTitle: 'সড়ক ও বাইপাস',
    cmdRoadDesc: 'এনএইচ-১০ লাভা ডাইভারশন',
    cmdHelplinesTitle: 'হেল্পলাইন নম্বর',
    cmdHelplinesDesc: 'এনডিআরএফ ১০৭৮ ও ১১২',
    cmdMedicalTitle: 'চিকিৎসা কনভয়',
    cmdMedicalDesc: 'জরুরি ওষুধ ও খাদ্য',
    responseSos: '🚨 জরুরি বিপদ সংকেত শনাক্ত! সাইরেন চালু এবং এনডিআরএফ ১০৭৮ নম্বরে জিপিএস বার্তা পাঠানো হয়েছে।',
    responseShelters: '🏠 নিকটতম ত্রাণ শিবির: জেএন স্টেডিয়াম পোলো গ্রাউন্ডস (৩৪০/১২০০ ধারণক্ষমতা)। সাহায্য সামগ্রী মজুত।',
    responseWeather: '🌧️ আবহাওয়া বার্তা: মেঘালয় ও সিকিমে ভারী বৃষ্টিপাত অব্যাহত। পাহাড় ধসের ঝুঁকি ৮৭%।',
    responseRoad: '🛣️ সড়ক পরামর্শ: এনএইচ-১০ তিস্তা বাজার অবরুদ্ধ। জরুরি গাড়ি লাভা বাইপাস দিয়ে চালানো হচ্ছে।',
    responseHelplines: '📞 জরুরি হটলাইন: জাতীয় ১১২, এনডিআরএফ ১০৭৮, রাজ্য বিপর্যয় মোকাবিলা ১০৭০।',
    responseMedical: '🚑 চিকিৎসা কনভয়: প্রয়োজনীয় ওষুধ ও ত্রাণ সামগ্রী লাভা রোড দিয়ে নিরাপদে পৌঁছানো হচ্ছে।',
    replayAudio: '🔊 পুনরায় শুনুন',
    typeQuestionPlaceholder: 'প্রশ্ন লিখুন (যেমন: ত্রাণ শিবির, আবহাওয়া, সড়ক)...',
    aiSpokenResponse: 'এআই ভয়েস উত্তর',
    highRiskCorridors: 'উচ্চ ঝুঁকিপূর্ণ মহাসড়কসমূহ',
    blockedStatus: 'অবরুদ্ধ পথ',
    vulnerableStatus: 'ঝুঁকিপূর্ণ',
    clearStatus: 'খোলা পথ',
    spatialGisRadar: 'উত্তর-পূর্ব জিআইএস রাডার',
    liveTerrainSatellite: 'লাইভ ভূখণ্ড ও স্যাটেলাইট মানচিত্র',
    allLayers: 'সব স্তর',
    supplyVehicles: 'সরবরাহ যানবাহন',
    highwayCorridors: 'মহাসড়কসমূহ',
    vulnerableRoadZones: 'ঝুঁকিপূর্ণ সড়ক এলাকা',
    topoBasemap: 'ভূখণ্ড',
    satelliteBasemap: 'স্যাটেলাইট',
    legendTitle: 'মানচিত্র সূচক',
    legendConvoy: '🚚 সরবরাহ কনভয়',
    legendBlocked: '🔴 অবরুদ্ধ পথ',
    legendHighRisk: '🟡 ঝুঁকিপূর্ণ',
    legendClearPass: '🟢 খোলা পথ',
    logisticsTitle: 'এআই পথ অপ্টিমাইজেশন ও কনভয় ট্র্যাকার',
    logisticsSub: 'রিয়েল-টাইম জিপিএস ও বিকল্প পথ ব্যবস্থাপনা',
    activeConvoysCard: 'চলমান সক্রিয় কনভয়',
    criticalBlockagesCard: 'অবরুদ্ধ প্রধান সড়কসমূহ',
    passableRoutesCard: 'খোলা পাহাড়ি পথ',
    reRouteAdviceTitle: 'এআই বিকল্প পথের পরামর্শ',
    divertConvoysBtn: 'পথ পরিবর্তন করুন',
    tabConvoyFleet: '১. সরবরাহ কনভয়',
    tabAiRouting: '২. এআই পথ নির্দেশক',
    tabIsolatedVillages: '৩. বিচ্ছিন্ন গ্রামসমূহ',
    tabIvrAlerts: '৪. আইভিআর ও কল অ্যালার্ট',
    liveGpsText: 'লাইভ জিপিএস',
    approxDistrictText: 'আনুমানিক জেলা',
    tapToChangeMode: 'মোড পরিবর্তন করতে স্পর্শ করুন',
    simulateLandslide: 'ভূমিধস অনুকরণ ➔ পথ পরিবর্তন',
    resetSimulation: 'অনুকরণ রিসেট করুন',
    searchConvoyPlaceholder: 'পণ্য, গাড়ির নম্বর বা পথ দিয়ে খুঁজুন...',
    alertsTitle: 'বিপর্যয় আগাম সতর্কতা ও নিয়ন্ত্রণ কক্ষ',
    alertsSub: '২৪/৭ জরুরি হটলাইন সহায়তা',
    controlRoomsTitle: 'জরুরি নিয়ন্ত্রণ কক্ষের নম্বর',
    callEmergency: 'কল করুন',
    activeWarningsTitle: 'সক্রিয় সতর্কবার্তা',
    reportTitle: 'নাগরিক ও ফিল্ড বিপর্যয় রিপোর্ট',
    reportSub: 'ভূমিধস বা সড়ক ক্ষতির রিপোর্ট জমা দিন',
    reportType: 'ঘটনার ধরন',
    submitReportBtn: 'রিপোর্ট জমা দিন',
    uploadPhoto: 'ছবি আপলোড করুন',
    locationGeotag: 'জিপিএস অবস্থান',
    description: 'বিস্তারিত বিবরণ',
    sensorsTitle: 'আইওটি সেন্সর ও পাহাড়ি ঢাল নজরদারি',
    sensorsSub: 'রিয়েল-টাইম ভূতাত্ত্বিক সেন্সর ডেটা',
    soilMoisture: 'মাটির আর্দ্রতা',
    rainfallGauge: 'বৃষ্টি পরিমাপক',
    tiltAngle: 'ঢাল কোণ',
    porePressure: 'জলীয় চাপ',
    liveStatus: 'লাইভ স্থিতি',
    settingsTitle: 'সিস্টেম সেটিংস ও পছন্দসমূহ',
    settingsSub: 'ভাষা, মানচিত্রের স্তর ও পরিচিতি পরিচালনা করুন',
    languageLabel: 'ভাষা নির্বাচন করুন',
    themeLabel: 'অ্যাপ থিম',
    notificationsLabel: 'জরুরি নোটিফিকেশন',
    userProfile: 'ব্যবহারকারী প্রোফাইল',
  },
  kha: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Surok Accessibility Grid',
    dashboard: 'Dashboard',
    alerts: 'Jingma & Warning',
    report: 'Phah Report',
    sensors: 'Sensors Data',
    settings: 'Settings',
    sosEmergency: 'SOS JINGEH',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Lok & Kur',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ap ya ki bthah ktien...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Phet Shaki Shngiam Wut Wut',
    readOfficialBulletin: 'Pule Jingkyntu Sorkar',
    broadcastSMS: 'Phah SMS 📱',
    helplines: 'Helplines Jingeh',
    shelters: 'Shnong Jingshngiam',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'KI BTHAH KTIEN:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Shnong Shngiam',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Jinghap Slap',
    cmdWeatherDesc: 'Rainfall & Landslide Risk',
    cmdRoadTitle: 'Surok & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Dawai & Jingbam',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS detected! Siren ba heh ka sawa bad la phah GPS sha NDRF 1078.',
    responseShelters: '🏠 Shnong Jingshngiam: JN Stadium Polo Grounds (340/1200 Capacity). Don ki dawai bad jingbam.',
    responseWeather: '🌧️ Jinghap Slap: U slap u jur bha ha Meghalaya & Sikkim. Ka jaka ka la ktah 87%.',
    responseRoad: '🛣️ Surok NH-10: Teesta Bazaar la khang. Ki kali ki iaid lyngba ka surok Lava.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Essential Convoy: Ki dawai bad marbam la pyniaid beit lyngba ka Lava bypass.',
    replayAudio: '🔊 Sngap Biang',
    typeQuestionPlaceholder: 'Thoh jingkylli (Shnong Shngiam, Slap, Surok)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'Ki Surok Bah ba Ma Bha',
    blockedStatus: 'La Khang',
    vulnerableStatus: 'Ba Ma',
    clearStatus: 'Ba Lait',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'Baroh ki Layer',
    supplyVehicles: 'Kali kit Marbam',
    highwayCorridors: 'Surok Bah',
    vulnerableRoadZones: 'Jaka ba Ma bha',
    topoBasemap: 'Topo',
    satelliteBasemap: 'Satellite',
    legendTitle: 'LEGEND',
    legendConvoy: '🚚 Kali Convoy',
    legendBlocked: '🔴 Surok ba Khang',
    legendHighRisk: '🟡 Surok ba Ma',
    legendClearPass: '🟢 Surok ba Lait',
    logisticsTitle: 'AI Dynamic Route & Convoy Tracker',
    logisticsSub: 'Live GPS & Surok ba Iaid Reroute',
    activeConvoysCard: 'Ki Kali ba Iaid lynti',
    criticalBlockagesCard: 'Ki Surok ba Khang',
    passableRoutesCard: 'Ki Surok Lum ba Lait',
    reRouteAdviceTitle: 'AI JINGAI JINGMUT SUROK',
    divertConvoysBtn: 'Pynphai Surok',
    tabConvoyFleet: '1. Kali Convoy',
    tabAiRouting: '2. AI Surok Routing',
    tabIsolatedVillages: '3. Shnong ba Shah Kut',
    tabIvrAlerts: '4. IVR & Phone Alerts',
    liveGpsText: 'Live GPS',
    approxDistrictText: 'District Location',
    tapToChangeMode: 'Kylliang Mode',
    simulateLandslide: 'Pynkhih Landslide ➔ Pynphai Surok',
    resetSimulation: 'Reset Simulation',
    searchConvoyPlaceholder: 'Wad kali da cargo, number, surok...',
    alertsTitle: 'Jingkyntu Jingeh & Control Rooms',
    alertsSub: '24/7 Hotlines Jingiarap',
    controlRoomsTitle: 'Hotlines Jingiarap',
    callEmergency: 'Phone Wut Wut',
    activeWarningsTitle: 'Jingkyntu ba Sawa',
    reportTitle: 'Phah Report Surok & Landslide',
    reportSub: 'Report ba thymmai na ka jaka',
    reportType: 'Jait Jingeh',
    submitReportBtn: 'Phah Report',
    uploadPhoto: 'Thep Dur',
    locationGeotag: 'GPS Jaka',
    description: 'Batai Bniah',
    sensorsTitle: 'IoT Sensors & Jingkhyllah Lum',
    sensorsSub: 'Data ba biang na ki sensor',
    soilMoisture: 'Ka Sngem Khyndew',
    rainfallGauge: 'Jingthew Slap',
    tiltAngle: 'Jingnoh Lum',
    porePressure: 'Pore Pressure',
    liveStatus: 'Live Status',
    settingsTitle: 'Settings & Ktien',
    settingsSub: 'Pynkylla Ktien, Theme & Contacts',
    languageLabel: 'Jied Ktien',
    themeLabel: 'App Theme',
    notificationsLabel: 'Jingpyntip Jingeh',
    userProfile: 'Profile Nongpyndonkam',
  },
  gar: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Smart Logistics Grid',
    dashboard: 'Dashboard',
    alerts: 'Mikrakani',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS KENANI',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Ma·drang & Ripel',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ku·rang knaenga...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Re·angbo Shngiamchi Wut Wut',
    readOfficialBulletin: 'Poraibo Nokgipa Sea',
    broadcastSMS: 'Watbo SMS 📱',
    helplines: 'Helplines Dakchakan',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'KU·RANG BTHAH:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Mikka Waani',
    cmdWeatherDesc: 'Rainfall & Hazard Risk',
    cmdRoadTitle: 'Rama & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Sam & Chaani',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS detected! Siren gam·ataha aro GPS-ko NDRF 1078-ona watataha.',
    responseShelters: '🏠 Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Chaani aro sam donga.',
    responseWeather: '🌧️ Mikka Waani: Meghalaya aro Sikkim-o mikka jame waaenga. A·solani 87% donga.',
    responseRoad: '🛣️ Rama Advisory: NH-10 Teesta Bazaar champenga. Gari Lava bypass rama gita re·enga.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Essential Convoy: Sam aro cha·anirangko Lava rama gita sorkari watatenga.',
    replayAudio: '🔊 Knapil·tai',
    typeQuestionPlaceholder: 'Segibo sing·ani (Relief Camp, Mikka, Rama)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'Kenani Gnanggipa Ramarang',
    blockedStatus: 'Champenga',
    vulnerableStatus: 'Kenani',
    clearStatus: 'Gital',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'Pilak Layer-rang',
    supplyVehicles: 'Cha·ani Gari',
    highwayCorridors: 'Highway Ramarang',
    vulnerableRoadZones: 'Kenani A·brang',
    topoBasemap: 'Topo',
    satelliteBasemap: 'Satellite',
    legendTitle: 'LEGEND',
    legendConvoy: '🚚 Convoy Gari',
    legendBlocked: '🔴 Champenggipa Rama',
    legendHighRisk: '🟡 Kenani Rama',
    legendClearPass: '🟢 Re·na Man·gipa Rama',
    logisticsTitle: 'AI Dynamic Route & Convoy Tracker',
    logisticsSub: 'Live GPS aro Rama Reroute Engine',
    activeConvoysCard: 'Re·enggipa Garirang',
    criticalBlockagesCard: 'Champenggipa Ramarang',
    passableRoutesCard: 'Re·na Man·gipa A·bri Rama',
    reRouteAdviceTitle: 'AI RAMA DIVERSE SALI',
    divertConvoysBtn: 'Rama Dingtangatbo',
    tabConvoyFleet: '1. Gari Pal',
    tabAiRouting: '2. AI Rama Routing',
    tabIsolatedVillages: '3. Champenggipa Songsarek',
    tabIvrAlerts: '4. IVR & Phone Alerts',
    liveGpsText: 'Live GPS',
    approxDistrictText: 'District Location',
    tapToChangeMode: 'Dingtangatbo Mode',
    simulateLandslide: 'A·solani Demo ➔ Rama Dingtangatbo',
    resetSimulation: 'Reset Demo',
    searchConvoyPlaceholder: 'Sandibo gari number, rama...',
    alertsTitle: 'Kenani Mikrakani & Control Room',
    alertsSub: '24/7 Dakchakan Helpline',
    controlRoomsTitle: 'Emergency Helpline Number',
    callEmergency: 'Ringbo Wut Wut',
    activeWarningsTitle: 'Mikrakani Gnanggipa',
    reportTitle: 'A·solani aro Rama Report',
    reportSub: 'Gital report watbo',
    reportType: 'Kenani Jat',
    submitReportBtn: 'Report Watbo',
    uploadPhoto: 'Photo Gatbo',
    locationGeotag: 'GPS Biap',
    description: 'Name Sebo',
    sensorsTitle: 'IoT Sensors aro A·bri Monitoring',
    sensorsSub: 'Real-time sensor data',
    soilMoisture: 'A·ani Chi',
    rainfallGauge: 'Mikka Thewani',
    tiltAngle: 'A·bri Dingchokani',
    porePressure: 'Chi Draani',
    liveStatus: 'Live Status',
    settingsTitle: 'Settings aro Ku·sik',
    settingsSub: 'Ku·sik, Theme & Contacts dingtangatbo',
    languageLabel: 'Ku·sik Seokbo',
    themeLabel: 'App Theme',
    notificationsLabel: 'Mikrakatani',
    userProfile: 'User Profile',
  },
  mni: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'ꯑꯦꯑꯥꯏ ꯂꯣꯖꯤꯁ꯭ꯇꯤꯛꯁ & ꯂꯝꯕꯤ ꯒ꯭ꯔꯤꯗ',
    dashboard: 'ꯗꯦꯁꯕꯣꯔꯗ',
    alerts: 'ꯆꯦꯛꯁꯤꯟꯋꯥ',
    report: 'ꯔꯤꯄꯣꯔꯠ',
    sensors: 'ꯁꯦꯟꯁꯔ',
    settings: 'ꯁꯦꯇꯤꯡꯁ',
    sosEmergency: 'ꯑꯀꯅꯕ ꯑꯦꯁ.ꯑꯣ.ꯑꯦꯁ',
    signIn: 'ꯁꯥꯏꯟ ꯏꯟ',
    signOut: 'ꯁꯥꯏꯟ ꯑꯥꯎꯠ',
    emergencyContacts: 'ꯏꯃꯨꯡ-ꯃꯅꯨꯡ',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'ꯈꯣꯟꯊꯣꯛ ꯇꯥꯕ꯭ꯔꯤ...',
    redAlert: 'ꯔꯦꯗ ꯑꯦꯂꯥꯔꯠ - ꯂꯦꯕꯦꯜ ꯴',
    evacuateNow: 'ꯊꯨꯅꯥ ꯅꯥꯅꯕ ꯃꯐꯝꯗ ꯆꯠꯂꯨ',
    readOfficialBulletin: 'ꯑꯣꯐꯤꯁꯤꯑꯦꯜ ꯕꯨꯂꯦꯇꯤꯟ ꯄꯥꯕꯤꯌꯨ',
    broadcastSMS: 'SMS ꯊꯥꯕꯤꯌꯨ 📱',
    helplines: 'ꯏꯃꯔꯖꯦꯟꯁꯤ ꯍꯦꯜꯄꯂꯥꯏꯟ',
    shelters: 'ꯔꯤꯂꯤꯐ ꯀꯦꯝꯞ',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'ꯈꯣꯟꯊꯣꯛ ꯊꯧꯔꯥꯡ:',
    cmdSosTitle: 'ꯑꯀꯅꯕ ꯑꯦꯁ.ꯑꯣ.ꯑꯦꯁ',
    cmdSosDesc: 'ꯁꯥꯏꯔꯦꯟ + ꯖꯤ.ꯄꯤ.ꯑꯦꯁ',
    cmdSheltersTitle: 'ꯔꯤꯂꯤꯐ ꯀꯦꯝꯞ',
    cmdSheltersDesc: 'ꯅꯥꯅꯕ ꯃꯐꯝꯁꯤꯡ',
    cmdWeatherTitle: 'ꯅꯣꯡ ꯆꯨꯕ',
    cmdWeatherDesc: 'ꯅꯣꯡ ꯑꯃꯁꯨꯡ ꯂꯩꯃꯥꯌ',
    cmdRoadTitle: 'ꯂꯝꯕꯤ ꯑꯃꯁꯨꯡ ꯕꯥꯏꯄꯥꯁ',
    cmdRoadDesc: 'ꯑꯦꯟ.ꯑꯩꯆ-꯱꯰ ꯂꯥꯚꯥ',
    cmdHelplinesTitle: 'ꯍꯦꯜꯄꯂꯥꯏꯟ ꯅꯝꯕꯔ',
    cmdHelplinesDesc: 'ꯑꯦꯟ.ꯗꯤ.ꯑꯔ.ꯑꯦꯐ ꯱꯰꯷꯸',
    cmdMedicalTitle: 'ꯍꯤꯗꯥꯛ-ꯂꯥꯡꯊꯛ ꯒꯥꯔꯤ',
    cmdMedicalDesc: 'ꯃꯔꯨꯑꯣꯏꯕ ꯄꯣꯠꯂꯝ',
    responseSos: '🚨 Emergency SOS Detected! Siren activate toure amasung GPS location NDRF 1078 da thakhre.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Hidag amasung chinjak leiri.',
    responseWeather: '🌧️ Weather Advisory: Meghalaya amasung Sikkim da akanba nong churi. Chingrum tubagi risk 87% leiri.',
    responseRoad: '🛣️ Route Advisory: NH-10 Teesta Bazaar thingjinre. Emergency gari Lava bypass lamda chatli.',
    responseHelplines: '📞 Emergency Helplines: National 112, NDRF 1078, State Control 1070.',
    responseMedical: '🚑 Essential Convoy: Hidag amasung ration Lava lamda safe oina pukhre.',
    replayAudio: '🔊 ꯑꯃꯨꯛ ꯇꯥꯕꯤꯌꯨ',
    typeQuestionPlaceholder: 'ꯋꯥꯍꯪ ꯏꯌꯨ (ꯔꯤꯂꯤꯐ ꯀꯦꯝꯞ, ꯅꯣꯡ, ꯂꯝꯕꯤ)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'ꯑꯀꯅꯕ ꯈꯨꯗꯣꯡꯊꯤꯕ ꯂꯝꯕꯤꯁꯤꯡ',
    blockedStatus: 'ꯊꯤꯡꯖꯤꯅꯕ',
    vulnerableStatus: 'ꯈꯨꯗꯣꯡꯊꯤꯕ',
    clearStatus: 'ꯂꯝꯕꯤ ꯄꯤꯕ',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'ꯂꯦꯌꯔ ꯄꯨꯝꯅꯃꯛ',
    supplyVehicles: 'ꯆꯤꯟꯖꯥꯛ ꯒꯥꯔꯤꯁꯤꯡ',
    highwayCorridors: 'ꯃꯔꯨꯑꯣꯏꯕ ꯂꯝꯕꯤꯁꯤꯡ',
    vulnerableRoadZones: 'ꯈꯨꯗꯣꯡꯊꯤꯕ ꯃꯐꯝ',
    topoBasemap: 'ꯇꯣꯄꯣ',
    satelliteBasemap: 'ꯁꯦꯇꯦꯂꯥꯏꯠ',
    legendTitle: 'ꯃꯦꯞ ꯈꯨꯗꯝ',
    legendConvoy: '🚚 ꯀꯅꯚꯣꯏ',
    legendBlocked: '🔴 ꯊꯤꯡꯖꯤꯅꯕ ꯂꯝꯕꯤ',
    legendHighRisk: '🟡 ꯈꯨꯗꯣꯡꯊꯤꯕ ꯂꯝꯕꯤ',
    legendClearPass: '🟢 ꯆꯠꯄ ꯌꯥꯕ ꯂꯝꯕꯤ',
    logisticsTitle: 'AI Route Optimization & Convoy Tracker',
    logisticsSub: 'Live GPS & Route Diversion Engine',
    activeConvoysCard: 'ꯆꯠꯂꯤꯕ ꯒꯥꯔꯤ ꯀꯅꯚꯣꯏ',
    criticalBlockagesCard: 'ꯊꯤꯡꯖꯤꯜꯂꯕ ꯂꯝꯕꯤꯁꯤꯡ',
    passableRoutesCard: 'ꯆꯠꯄ ꯌꯥꯕ ꯂꯝꯕꯤꯁꯤꯡ',
    reRouteAdviceTitle: 'AI ꯑꯇꯣꯞꯄ ꯂꯝꯕꯤ ꯄꯔꯥꯃꯔꯁ',
    divertConvoysBtn: 'ꯂꯝꯕꯤ ꯍꯣꯡꯗꯣꯛꯎ',
    tabConvoyFleet: '꯱. ꯒꯥꯔꯤ ꯀꯅꯚꯣꯏ',
    tabAiRouting: '꯲. AI ꯂꯝꯕꯤ ꯈꯪꯗꯣꯛꯄ',
    tabIsolatedVillages: '꯳. ꯂꯝꯕꯤ ꯊꯤꯡꯖꯤꯜꯂꯕ ꯈꯨꯜ',
    tabIvrAlerts: '꯴. IVR ꯑꯃꯁꯨꯡ ꯀꯣꯜ',
    liveGpsText: 'ꯂꯥꯏꯚ GPS',
    approxDistrictText: 'ꯗꯤꯁ꯭ꯠꯔꯤꯛ ꯃꯐꯝ',
    tapToChangeMode: 'ꯃꯣꯗ ꯍꯣꯡꯗꯣꯛꯄ',
    simulateLandslide: 'ꯂꯩꯃꯥꯌ ꯇꯨꯕ ꯗꯦꯃꯣ ➔ ꯂꯝꯕꯤ ꯍꯣꯡꯗꯣꯛꯎ',
    resetSimulation: 'ꯗꯦꯃꯣ ꯔꯤꯁꯦꯠ',
    searchConvoyPlaceholder: 'ꯄꯣꯠꯂꯝ, ꯒꯥꯔꯤ ꯅꯝꯕꯔ ꯊꯤꯕ...',
    alertsTitle: 'ꯆꯦꯛꯁꯤꯟꯋꯥ & ꯀꯟꯠꯔꯣꯜ ꯔꯨꯃꯁꯤꯡ',
    alertsSub: '꯲꯴/꯷ ꯏꯃꯔꯖꯦꯟꯁꯤ ꯍꯦꯜꯄꯂꯥꯏꯟ',
    controlRoomsTitle: 'ꯏꯃꯔꯖꯦꯟꯁꯤ ꯍꯦꯜꯄꯂꯥꯏꯟ ꯅꯝꯕꯔ',
    callEmergency: 'ꯀꯣꯜ ꯇꯧꯕꯤꯌꯨ',
    activeWarningsTitle: 'ꯆꯠꯊꯔꯤꯕ ꯆꯦꯛꯁꯤꯟꯋꯥ',
    reportTitle: 'ꯂꯩꯃꯥꯌ ꯇꯨꯕ ꯔꯤꯄꯣꯔꯠ ꯇꯧꯕ',
    reportSub: 'ꯑꯅꯧꯕ ꯔꯤꯄꯣꯔꯠ ꯄꯤꯕ',
    reportType: 'ꯊꯧꯗꯣꯛ ꯃꯈꯜ',
    submitReportBtn: 'ꯔꯤꯄꯣꯔꯠ ꯄꯤꯌꯨ',
    uploadPhoto: 'ꯐꯣꯇꯣ ꯊꯥꯕꯤꯌꯨ',
    locationGeotag: 'GPS ꯃꯐꯝ',
    description: 'ꯑꯀꯨꯞꯄ ꯃꯔꯨꯑꯣꯏꯕ',
    sensorsTitle: 'IoT ꯁꯦꯟꯁꯔ ꯑꯃꯁꯨꯡ ꯆꯤꯡ ꯌꯦꯡꯁꯤꯟꯕ',
    sensorsSub: 'ꯔꯤꯌꯜ-ꯇꯥꯏꯝ ꯁꯦꯟꯁꯔ ꯗꯥꯇꯥ',
    soilMoisture: 'ꯂꯩꯃꯥꯌ ꯏꯁꯤꯡ',
    rainfallGauge: 'ꯅꯣꯡ ꯆꯨꯕ ꯃꯥꯞ',
    tiltAngle: 'ꯆꯤꯡ ꯇꯨꯕ ꯀꯣꯟ',
    porePressure: 'ꯏꯁꯤꯡ ꯄ꯭ꯔꯦꯁꯔ',
    liveStatus: 'ꯂꯥꯏꯚ ꯐꯤꯚꯝ',
    settingsTitle: 'ꯁꯦꯇꯤꯡꯁ & ꯂꯣꯟ',
    settingsSub: 'ꯂꯣꯟ, ꯊꯤꯝ ꯑꯃꯁꯨꯡ ꯀꯟꯇꯦꯛ ꯁꯦꯝꯖꯤꯟꯕ',
    languageLabel: 'ꯂꯣꯟ ꯈꯟꯕꯤꯌꯨ',
    themeLabel: 'ꯑꯦꯞ ꯊꯤꯝ',
    notificationsLabel: 'ꯆꯦꯛꯁꯤꯟ ꯄꯥꯎ',
    userProfile: 'ꯌꯨꯖꯔ ꯄ꯭ꯔꯣꯐꯥꯏꯜ',
  },
  mzo: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Kawngpui Grid',
    dashboard: 'Dashboard',
    alerts: 'Vantlang Warning',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS HLAMAU',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Chhungkua & Thiante',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ngaihthlak lai...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Insawn nghal rawh',
    readOfficialBulletin: 'Chhiar Rawh Bulletin',
    broadcastSMS: 'Thawn Rawh SMS 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Ruah Sur Dan',
    cmdWeatherDesc: 'Rainfall & Hazard',
    cmdRoadTitle: 'Kawng & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Damdawi & Chaw',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS hmuh a ni! Siren a ri a, GPS SOS chu NDRF 1078-ah thawn nghal a ni.',
    responseShelters: '🏠 Hnaivai ber Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Damdawi leh ei tur a awm.',
    responseWeather: '🌧️ Khawchin: Meghalaya leh Sikkim-ah ruah nasa takin a sur a. Lei min theihna 87% a tling.',
    responseRoad: '🛣️ Kawng Chanchin: NH-10 Teesta Bazaar a ping a. Emergency motor chu Lava kawngah kualtir a ni.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Damdawi Convoy: Damdawi leh chaw chu Lava kawngah him takin thawn a ni.',
    replayAudio: '🔊 Ngaithla Nawn Rawh',
    typeQuestionPlaceholder: 'Zawhna ziak rawh (Shelters, Ruah, Kawng)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'Kawngpui Hlauthawngawmte',
    blockedStatus: 'Ping',
    vulnerableStatus: 'Hlauhawm',
    clearStatus: 'Tlang',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'Layer Zawng Zawng',
    supplyVehicles: 'Supply Motor-te',
    highwayCorridors: 'Highway Kawngpuite',
    vulnerableRoadZones: 'Hmun Hlauhawmte',
    topoBasemap: 'Topo',
    satelliteBasemap: 'Satellite',
    legendTitle: 'LEGEND',
    legendConvoy: '🚚 Convoy Motor',
    legendBlocked: '🔴 Kawng Ping',
    legendHighRisk: '🟡 Kawng Hlauhawm',
    legendClearPass: '🟢 Kawng Tlang',
    logisticsTitle: 'AI Dynamic Route & Convoy Tracker',
    logisticsSub: 'Live GPS leh Kawng Kual Engine',
    activeConvoysCard: 'Motor Tlan Meka-te',
    criticalBlockagesCard: 'Kawng Pingte',
    passableRoutesCard: 'Kawng Tlangtheite',
    reRouteAdviceTitle: 'AI KAWNG DANG KUAL THURAWN',
    divertConvoysBtn: 'Kawng Kualtir Rawh',
    tabConvoyFleet: '1. Motor Rual',
    tabAiRouting: '2. AI Kawng Zawnna',
    tabIsolatedVillages: '3. Khua Pingte',
    tabIvrAlerts: '4. IVR leh Phone Alerts',
    liveGpsText: 'Live GPS',
    approxDistrictText: 'District Hmun',
    tapToChangeMode: 'Thlak Rawh Mode',
    simulateLandslide: 'Lei Min Simulation ➔ Kawng Kualtir',
    resetSimulation: 'Reset Simulation',
    searchConvoyPlaceholder: 'Zong rawh bungraw, number, kawng...',
    alertsTitle: 'Vantlang Warning & Control Rooms',
    alertsSub: '24/7 Tanpuina Helpline',
    controlRoomsTitle: 'Emergency Helpline Number-te',
    callEmergency: 'Phone nghal rawh',
    activeWarningsTitle: 'Warning Thuchhuakte',
    reportTitle: 'Lei Min leh Kawng Chhe Report',
    reportSub: 'Report thar thehlut rawh',
    reportType: 'Chhiatna Chi',
    submitReportBtn: 'Thehlut Rawh',
    uploadPhoto: 'Thlalak Dah Rawh',
    locationGeotag: 'GPS Hmun',
    description: 'Chipchiar takin ziak rawh',
    sensorsTitle: 'IoT Sensors & Tlang Stability',
    sensorsSub: 'Real-time sensor data',
    soilMoisture: 'Leilung Hnawng',
    rainfallGauge: 'Ruah Sur Tehna',
    tiltAngle: 'Awih Dan',
    porePressure: 'Tui Nawrna',
    liveStatus: 'Live Status',
    settingsTitle: 'Settings leh Tawng',
    settingsSub: 'Tawng, Theme & Contacts thlakna',
    languageLabel: 'Tawng Thlang Rawh',
    themeLabel: 'App Theme',
    notificationsLabel: 'Warning Hriattirna',
    userProfile: 'User Profile',
  },
  kok: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Lama Grid',
    dashboard: 'Dashboard',
    alerts: 'Warning',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS DANGER',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Lok & Nogor',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Khorang Khnagjakphai...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Thangbo Safe Place-o',
    readOfficialBulletin: 'Read Official Bulletin',
    broadcastSMS: 'Send SMS 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX AI Voice Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Noh Watnai',
    cmdWeatherDesc: 'Rainfall & Saturation',
    cmdRoadTitle: 'Lama & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supplies',
    responseSos: '🚨 Emergency SOS detected! Siren rwjakha tei GPS SOS NDRF 1078-o thangkha.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Sam tei chakhwtal tongo.',
    responseWeather: '🌧️ Noh Watnai: Meghalaya tei Sikkim-o nokha kwbang watlai tongo. Hazard risk 87%.',
    responseRoad: '🛣️ Lama Advisory: NH-10 Teesta Bazaar borkha. Garirok Lava bypass lama bai thango.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Medical Supply: Essential sam tei ration Lava lama bai safe-o thangkha.',
    replayAudio: '🔊 Khorang Khnabil',
    typeQuestionPlaceholder: 'Songjakbai sei (Shelters, Noh, Lama)...',
    aiSpokenResponse: 'AI Spoken Response',
    highRiskCorridors: 'High-Risk Lamrok',
    blockedStatus: 'Borkha',
    vulnerableStatus: 'Risk Tongo',
    clearStatus: 'Khurang',
    spatialGisRadar: 'NER Spatial GIS Radar',
    liveTerrainSatellite: 'Live Terrain & Satellite GIS',
    allLayers: 'Jotog Layer',
    supplyVehicles: 'Supply Garirok',
    highwayCorridors: 'Highway Lamrok',
    vulnerableRoadZones: 'Risk Road Zones',
    topoBasemap: 'Topo',
    satelliteBasemap: 'Satellite',
    legendTitle: 'LEGEND',
    legendConvoy: '🚚 Convoy',
    legendBlocked: '🔴 Borkha Lama',
    legendHighRisk: '🟡 Risk Lama',
    legendClearPass: '🟢 Khurang Lama',
    logisticsTitle: 'AI Dynamic Route & Convoy Tracker',
    logisticsSub: 'Live GPS & Route Diversion Engine',
    activeConvoysCard: 'Thanglaigwi Tongnai Garirok',
    criticalBlockagesCard: 'Borkhai Tongnai Lamrok',
    passableRoutesCard: 'Khurang Hachuk Lamrok',
    reRouteAdviceTitle: 'AI LAMA SLIKNAI SALI',
    divertConvoysBtn: 'Lama Slikdi',
    tabConvoyFleet: '1. Garirok',
    tabAiRouting: '2. AI Lama Routing',
    tabIsolatedVillages: '3. Borkha Kami',
    tabIvrAlerts: '4. IVR & Phone Alerts',
    liveGpsText: 'Live GPS',
    approxDistrictText: 'District Location',
    tapToChangeMode: 'Mode Slikdi',
    simulateLandslide: 'Hachuk Boli Simulation ➔ Lama Slikdi',
    resetSimulation: 'Reset Simulation',
    searchConvoyPlaceholder: 'Naitukdi gari number, cargo, lama...',
    alertsTitle: 'Disaster Warning & Control Rooms',
    alertsSub: '24/7 Helpline Dakchakan',
    controlRoomsTitle: 'Emergency Helpline Number',
    callEmergency: 'Phone Khlai',
    activeWarningsTitle: 'Active Warnings',
    reportTitle: 'Hachuk Boli & Lama Report',
    reportSub: 'Kwtal report tisadi',
    reportType: 'Jat',
    submitReportBtn: 'Report Tisadi',
    uploadPhoto: 'Photo Rwdi',
    locationGeotag: 'GPS Location',
    description: 'Brogwina Sei',
    sensorsTitle: 'IoT Sensors & Slope Stability',
    sensorsSub: 'Real-time sensor data',
    soilMoisture: 'Ha Kwthwk',
    rainfallGauge: 'Noh Thewnai',
    tiltAngle: 'Hachuk Angle',
    porePressure: 'Twi Pressure',
    liveStatus: 'Live Status',
    settingsTitle: 'Settings & Kok',
    settingsSub: 'Kok, Theme & Contacts slikdi',
    languageLabel: 'Kok Seokdi',
    themeLabel: 'App Theme',
    notificationsLabel: 'Warning Khnangnai',
    userProfile: 'User Profile',
  },
  ne: {
    appTitle: 'लॉजिक्स-एनईआर',
    appSubtitle: 'एआई आपूर्ति र मार्ग सुगमयता ग्रिड',
    dashboard: 'ड्यासबोर्ड',
    alerts: 'चेतावनीहरू',
    report: 'रिपोर्ट पठाउनुहोस्',
    sensors: 'सेन्सर डाटा',
    settings: 'सेटिङ्हरू',
    sosEmergency: 'आपत्कालीन एसओएस',
    signIn: 'साइन इन गर्नुहोस्',
    signOut: 'साइन आउट',
    emergencyContacts: 'आपत्कालीन सम्पर्कहरू (परिवार र साथीहरू)',
    voiceMicTooltip: 'लॉजिक्स एआई सहायक',
    listeningVoice: 'आवाज आदेश सुन्दैछ...',
    redAlert: 'रेड अलर्ट - स्तर ४',
    evacuateNow: 'तुरुन्तै सुरक्षित स्थानमा जानुहोस्',
    readOfficialBulletin: 'आधिकारिक समाचार पढ्नुहोस्',
    broadcastSMS: 'एसएमएस पठाउनुहोस् 📱',
    helplines: 'आपत्कालीन हेल्पलाइनहरू',
    shelters: 'राहत शिविरहरू',
    voiceAssistantTitle: 'लॉजिक्स एआई भ्वाइस सहायक',
    voiceAssistantSub: 'उत्तर-पूर्व क्षेत्रीय ग्रिड',
    quickCommandsTitle: 'द्रुत भ्वाइस कमान्डहरू:',
    cmdSosTitle: 'आपत्कालीन एसओएस',
    cmdSosDesc: 'साइरन + जीपीएस सन्देश',
    cmdSheltersTitle: 'राहत शिविरहरू',
    cmdSheltersDesc: 'नजिकको सुरक्षित शिविर',
    cmdWeatherTitle: 'मनसुन मौसम',
    cmdWeatherDesc: 'वर्षा र पहिरो जोखिम',
    cmdRoadTitle: 'सडक र बाइपास',
    cmdRoadDesc: 'एनएच-१० लाभा मार्ग',
    cmdHelplinesTitle: 'हेल्पलाइन नम्बरहरू',
    cmdHelplinesDesc: 'एनडीआरएफ १०७८ र ११२',
    cmdMedicalTitle: 'चिकित्सा आपूर्ति',
    cmdMedicalDesc: 'अत्यावश्यक राहत सामग्री',
    responseSos: '🚨 आपत्कालीन जोखिम पत्ता लाग्यो! साइरन बज्यो र एनडीआरएफ १०७८ मा जीपीएस स्थान पठाइयो।',
    responseShelters: '🏠 नजिकको राहत शिविर: जेएन स्टेडियम पोलो ग्राउन्ड्स (३४०/१२०० क्षमता)। खाना र औषधि उपलब्ध छ।',
    responseWeather: '🌧️ मौसम सल्लाह: मेघालय र सिक्किममा भारी मनसुनी वर्षा जारी छ। पहिरो जोखिम ८७% छ।',
    responseRoad: '🛣️ सडक सल्लाह: एनएच-१० टिस्टा बजार अवरुद्ध छ। आपत्कालीन गाडीहरू लाभा बाइपासबाट पठाइएको छ।',
    responseHelplines: '📞 आपत्कालीन हेल्पलाइनहरू: राष्ट्रिय ११२, एनडीआरएफ १०७८, राज्य विपद् नियन्त्रण १०७०।',
    responseMedical: '🚑 चिकित्सा आपूर्ति: आवश्यक औषधि र राशन लाभा बाइपास मार्गबाट सुरक्षित पठाइएको छ।',
    replayAudio: '🔊 फेरि सुन्नुहोस्',
    typeQuestionPlaceholder: 'प्रश्न लेख्नुहोस् (जस्तै: राहत शिविर, मौसम, सडक)...',
    aiSpokenResponse: 'एआई भ्वाइस जवाफ',
    highRiskCorridors: 'उच्च जोखिम राजमार्ग मार्गहरू',
    blockedStatus: 'अवरुद्ध',
    vulnerableStatus: 'जोखिमपूर्ण',
    clearStatus: 'खुला बाटो',
    spatialGisRadar: 'एनईआर स्थानिक जीआईएस रडार',
    liveTerrainSatellite: 'प्रत्यक्ष भूभाग र उपग्रह नक्सा',
    allLayers: 'सबै तहहरू',
    supplyVehicles: 'आपूर्ति गाडीहरू',
    highwayCorridors: 'राजमार्ग मार्गहरू',
    vulnerableRoadZones: 'जोखिमपूर्ण सडक क्षेत्र',
    topoBasemap: 'टोपो',
    satelliteBasemap: 'उपग्रह',
    legendTitle: 'नक्सा संकेत',
    legendConvoy: '🚚 आपूर्ति गाडी',
    legendBlocked: '🔴 अवरुद्ध सडक',
    legendHighRisk: '🟡 उच्च जोखिम',
    legendClearPass: '🟢 खुला सडक',
    logisticsTitle: 'एआई गतिशील मार्ग अनुकूलन र कन्भोय ट्र्याकर',
    logisticsSub: 'प्रत्यक्ष जीपीएस र पहिरो बाइपास प्रणाली',
    activeConvoysCard: 'सक्रिय आपूर्ति कन्भोयहरू',
    criticalBlockagesCard: 'अवरुद्ध मुख्य सडकहरू',
    passableRoutesCard: 'खुला पहाडी मार्गहरू',
    reRouteAdviceTitle: 'एआई वैकल्पिक मार्ग सिफारिस',
    divertConvoysBtn: 'मार्ग बदल्नुहोस्',
    tabConvoyFleet: '१. आपूर्ति गाडीहरू',
    tabAiRouting: '२. एआई मार्ग नेभिगेसन',
    tabIsolatedVillages: '३. सम्पर्कविहीन गाउँहरू',
    tabIvrAlerts: '४. आईभीआर र फोन कलहरू',
    liveGpsText: 'लाइभ जीपीएस',
    approxDistrictText: 'जिल्ला स्थान',
    tapToChangeMode: 'मोड बदल्न छुनुहोस्',
    simulateLandslide: 'पहिरो सिमुलेसन ➔ वैकल्पिक मार्ग',
    resetSimulation: 'सिमुलेसन रिसेट गर्नुहोस्',
    searchConvoyPlaceholder: 'सामग्री, गाडी नम्बर वा मार्गबाट खोज्नुहोस्...',
    alertsTitle: 'विपद् पूर्व चेतावनी र नियन्त्रण कक्षहरू',
    alertsSub: '२४/७ आपत्कालीन हटलाइन सहायता',
    controlRoomsTitle: 'आपत्कालीन नियन्त्रण कक्ष नम्बरहरू',
    callEmergency: 'कल गर्नुहोस्',
    activeWarningsTitle: 'सक्रिय पूर्व चेतावनीहरू',
    reportTitle: 'नागरिक तथा फिल्ड विपद् रिपोर्ट',
    reportSub: 'पहिरो वा सडक क्षतिको प्रत्यक्ष विवरण पठाउनुहोस्',
    reportType: 'घटना प्रकार',
    submitReportBtn: 'रिपोर्ट पेश गर्नुहोस्',
    uploadPhoto: 'तस्वीर अपलोड गर्नुहोस्',
    locationGeotag: 'जीपीएस स्थान',
    description: 'विस्तृत विवरण',
    sensorsTitle: 'आईओटी सेन्सर र पहाडी स्थिरता',
    sensorsSub: 'प्रत्यक्ष भू-प्राविधिक सेन्सर ग्रिड डाटा',
    soilMoisture: 'माटोको चिस्यान',
    rainfallGauge: 'वर्षा मापक',
    tiltAngle: 'ढलान कोण',
    porePressure: 'पानीको चाप',
    liveStatus: 'प्रत्यक्ष स्थिति',
    settingsTitle: 'प्रणाली सेटिङ्हरू र क्षेत्रीय प्राथमिकता',
    settingsSub: 'भाषा, नक्सा तहहरू र सम्पर्कहरू व्यवस्थापन गर्नुहोस्',
    languageLabel: 'इन्टरफेस भाषा छान्नुहोस्',
    themeLabel: 'एप थिम',
    notificationsLabel: 'आपत्कालीन सूचनाहरू',
    userProfile: 'प्रयोगकर्ता प्रोफाइल',
  },
};

const LANGUAGE_KEY = 'logix_selected_language_v1';
let currentLang: LanguageCode = 'en';

export function getSelectedLanguage(): LanguageCode {
  if (typeof window === 'undefined' || !window.localStorage) return currentLang;
  try {
    const saved = window.localStorage.getItem(LANGUAGE_KEY) as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      currentLang = saved;
      return saved;
    }
  } catch {}
  return 'en';
}

export function setSelectedLanguage(lang: LanguageCode): void {
  currentLang = lang;
  if (typeof window === 'undefined' || !window.localStorage) return;
  try {
    window.localStorage.setItem(LANGUAGE_KEY, lang);
  } catch {}
}

export function getTranslations(lang: LanguageCode = getSelectedLanguage()): TranslationDictionary {
  return TRANSLATIONS[lang] || TRANSLATIONS['en'];
}
