/**
 * Seven Sister States Regional Language Translation Service
 * Supports 11 North Eastern & Regional Languages:
 * English, Hindi, Assamese, Bengali, Khasi, Garo, Manipuri, Mizo, Nagamese, Kokborok, Nepali
 */

export type LanguageCode =
  | 'en' // English
  | 'hi' // Hindi (हिन्दी)
  | 'as' // Assamese (অসমীয়া)
  | 'bn' // Bengali (বাংলা)
  | 'kha' // Khasi (Ka Ktien Khasi)
  | 'gar' // Garo (A·chik)
  | 'mni' // Manipuri / Meitei (ꯃꯩꯇꯩꯂꯣꯟ)
  | 'mzo' // Mizo (Mizo ṭawng)
  | 'nag' // Nagamese (Nagaland)
  | 'kok' // Kokborok (Tripura)
  | 'ne'; // Nepali (नेपाली)

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  region: string;
  flag: string;
  locale: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', region: 'Global / Standard', flag: '🇬🇧', locale: 'en-US' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'Common Regional', flag: '🇮🇳', locale: 'hi-IN' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'Assam', flag: '🌾', locale: 'as-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'Tripura / Assam', flag: '🇧🇩', locale: 'bn-IN' },
  { code: 'kha', name: 'Khasi', nativeName: 'Ka Ktien Khasi', region: 'Meghalaya', flag: '⛰️', locale: 'en-IN' },
  { code: 'gar', name: 'Garo', nativeName: 'A·chik', region: 'Meghalaya', flag: '🌿', locale: 'en-IN' },
  { code: 'mni', name: 'Manipuri', nativeName: 'ꯃꯩꯇꯩꯂꯣꯟ', region: 'Manipur', flag: '🏹', locale: 'en-IN' },
  { code: 'mzo', name: 'Mizo', nativeName: 'Mizo ṭawng', region: 'Mizoram', flag: '🏞️', locale: 'en-IN' },
  { code: 'nag', name: 'Nagamese', nativeName: 'Nagamese', region: 'Nagaland', flag: '🏔️', locale: 'en-IN' },
  { code: 'kok', name: 'Kokborok', nativeName: 'Kokborok', region: 'Tripura', flag: '🗣️', locale: 'en-IN' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', region: 'Sikkim', flag: '🏔️', locale: 'ne-NP' },
];

export interface TranslationDictionary {
  appTitle: string;
  appSubtitle: string;
  dashboard: string;
  alerts: string;
  report: string;
  sensors: string;
  settings: string;
  sosEmergency: string;
  signIn: string;
  signOut: string;
  emergencyContacts: string;
  voiceMicTooltip: string;
  listeningVoice: string;
  redAlert: string;
  evacuateNow: string;
  readOfficialBulletin: string;
  broadcastSMS: string;
  helplines: string;
  shelters: string;
  voiceAssistantTitle: string;
  voiceAssistantSub: string;
  quickCommandsTitle: string;
  cmdSosTitle: string;
  cmdSosDesc: string;
  cmdSheltersTitle: string;
  cmdSheltersDesc: string;
  cmdWeatherTitle: string;
  cmdWeatherDesc: string;
  cmdRoadTitle: string;
  cmdRoadDesc: string;
  cmdHelplinesTitle: string;
  cmdHelplinesDesc: string;
  cmdMedicalTitle: string;
  cmdMedicalDesc: string;
  responseSos: string;
  responseShelters: string;
  responseWeather: string;
  responseRoad: string;
  responseHelplines: string;
  responseMedical: string;
  replayAudio: string;
  typeQuestionPlaceholder: string;
  aiSpokenResponse: string;
}

export const TRANSLATIONS: Record<LanguageCode, TranslationDictionary> = {
  en: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Smart Logistics & Accessibility Grid',
    dashboard: 'Dashboard',
    alerts: 'Alerts',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS EMERGENCY',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Emergency Contacts (Friends & Family)',
    voiceMicTooltip: 'LOGIX AI Voice Assistant',
    listeningVoice: 'Listening for regional commands...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'EVACUATE IMMEDIATELY',
    readOfficialBulletin: 'Read Official Bulletin',
    broadcastSMS: 'Broadcast via SMS 📱',
    helplines: 'Emergency Hotlines',
    shelters: 'Relief Camps & Shelters',
    voiceAssistantTitle: 'LOGIX AI Voice Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Nearest Safe Camps',
    cmdWeatherTitle: 'Monsoon Weather',
    cmdWeatherDesc: 'Rainfall & Saturation',
    cmdRoadTitle: 'Road & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helplines',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency Distress Detected! Siren activated & GPS SOS dispatched to NDRF 1078.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Supplies active.',
    responseWeather: '🌧️ Weather Advisory: Heavy monsoon downpour continuing across Meghalaya & Sikkim. Slope saturation 87%.',
    responseRoad: '🛣️ Route Advisory: NH-10 Teesta Bazaar is blocked. Emergency traffic diverted via Lava pass.',
    responseHelplines: '📞 Emergency Hotlines: National 112, NDRF 1078, State Disaster Operation 1070.',
    responseMedical: '🚑 Medical Convoy Alert: Essential medicine & ration supplies cleared through Lava-Algarah bypass.',
    replayAudio: '🔊 Replay Audio',
    typeQuestionPlaceholder: 'Type a question (e.g. Shelters, Weather, NH-10)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  hi: {
    appTitle: 'लॉजिक्स-एनईआर',
    appSubtitle: 'एआई स्मार्ट लॉजिस्टिक्स एवं मार्ग ग्रिड',
    dashboard: 'डैशबोर्ड',
    alerts: 'चेतावनी',
    report: 'रिपोर्ट दर्ज करें',
    sensors: 'सेंसर डेटा',
    settings: 'सेटिंग्स',
    sosEmergency: 'आपातकालीन एसओएस',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट',
    emergencyContacts: 'आपातकालीन संपर्क (परिवार और मित्र)',
    voiceMicTooltip: 'लॉजिक्स एआई सहायक',
    listeningVoice: 'क्षेत्रीय आवाज कमांड सुन रहा है...',
    redAlert: 'रेड अलर्ट - स्तर 4',
    evacuateNow: 'तुरंत सुरक्षित स्थान पर जाएं',
    readOfficialBulletin: 'आधिकारिक बुलेटिन पढ़ें',
    broadcastSMS: 'एसएमएस से भेजें 📱',
    helplines: 'आपातकालीन हेल्पलाइन',
    shelters: 'राहत शिविर',
    voiceAssistantTitle: 'लॉजिक्स एआई वॉयस सहायक',
    voiceAssistantSub: 'उत्तर-पूर्व क्षेत्रीय ग्रिड',
    quickCommandsTitle: 'त्वरित वॉयस कमांड:',
    cmdSosTitle: 'आपातकालीन एसओएस',
    cmdSosDesc: 'सायरन + जीपीएस संदेश',
    cmdSheltersTitle: 'राहत शिविर',
    cmdSheltersDesc: 'निकटतम सुरक्षित शिविर',
    cmdWeatherTitle: 'मानसून मौसम',
    cmdWeatherDesc: 'बारिश और मिट्टी नमी',
    cmdRoadTitle: 'सड़क एवं बाईपास',
    cmdRoadDesc: 'एनएच-10 लावा मार्ग',
    cmdHelplinesTitle: 'हेल्पलाइन नंबर',
    cmdHelplinesDesc: 'एनडीआरएफ 1078 और 112',
    cmdMedicalTitle: 'चिकित्सा आपूर्ति',
    cmdMedicalDesc: 'आवश्यक राहत सामग्री',
    responseSos: '🚨 आपातकालीन खतरा दर्ज हुआ! सायरन सक्रिय और एनडीआरएफ 1078 को जीपीएस संदेश भेजा गया।',
    responseShelters: '🏠 निकटतम राहत शिविर: जेएन स्टेडियम पोलो ग्राउंड्स (340/1200 क्षमता)। खाद्य सामग्री उपलब्ध है।',
    responseWeather: '🌧️ मौसम सलाह: मेघालय और सिक्किम में भारी मानसूनी बारिश जारी है। ढलान संतृप्ति 87% है।',
    responseRoad: '🛣️ मार्ग सलाह: एनएच-10 तीस्ता बाजार बंद है। आपातकालीन यातायात लावा बाईपास से निकाला जा रहा है।',
    responseHelplines: '📞 आपातकालीन हेल्पलाइन: राष्ट्रीय 112, एनडीआरएफ 1078, राज्य आपदा नियंत्रण 1070।',
    responseMedical: '🚑 चिकित्सा काफिला: आवश्यक दवाएं और राशन लावा-अलगरह मार्ग से सुरक्षित निकाले जा रहे हैं।',
    replayAudio: '🔊 फिर से सुनें',
    typeQuestionPlaceholder: 'सवाल लिखें (जैसे: राहत शिविर, मौसम, सड़क मार्ग)...',
    aiSpokenResponse: 'एआई वॉयस उत्तर',
  },
  as: {
    appTitle: 'লজিক্স-এনইআৰ',
    appSubtitle: 'এআই স্মাৰ্ট লজিষ্টিকছ আৰু পথ সুগমতা',
    dashboard: 'ডেশ্ববৰ্ড',
    alerts: 'সতৰ্কবাৰ্তা',
    report: 'ৰিপৰ্ট',
    sensors: 'চেনচৰ',
    settings: 'চেটিংছ',
    sosEmergency: 'জৰুৰীকালীন এছ.অ.এছ',
    signIn: 'চাইন ইন',
    signOut: 'চাইন আউট',
    emergencyContacts: 'জৰুৰীকালীন যোগাযোগ (পৰিয়াল আৰু বন্ধু)',
    voiceMicTooltip: 'লজিক্স এআই সহায়ক',
    listeningVoice: 'কণ্ঠ নিৰ্দেশনা শুনি আছে...',
    redAlert: 'ৰেড এলাৰ্ট - স্তৰ ৪',
    evacuateNow: 'তাত্ক্ষণিক স্থানান্তৰ হওক',
    readOfficialBulletin: 'চৰকাৰী জাননী পঢ়ক',
    broadcastSMS: 'এছ.এম.এছ প্ৰেৰণ 📱',
    helplines: 'জৰুৰীকালীন হেল্পলাইন',
    shelters: 'আশ্ৰয় শিবিৰ',
    voiceAssistantTitle: 'লজিক্স এআই কণ্ঠ সহায়ক',
    voiceAssistantSub: 'উত্তৰ-পূৰ্বাঞ্চল আঞ্চলিক গ্ৰিড',
    quickCommandsTitle: 'দ্ৰুত কণ্ঠ নিৰ্দেশনা:',
    cmdSosTitle: 'জৰুৰী এছ.অ.এছ',
    cmdSosDesc: 'ছাইৰেন + জিপিএছ বাৰ্তা',
    cmdSheltersTitle: 'আশ্ৰয় শিবিৰ',
    cmdSheltersDesc: 'ওচৰৰ সুৰক্ষিত শিবিৰ',
    cmdWeatherTitle: 'বৰষুণৰ বতৰ',
    cmdWeatherDesc: 'বৃষ্টিপাত আৰু মাটিৰ আৰ্দ্ৰতা',
    cmdRoadTitle: 'পথ আৰু বাইপাছ',
    cmdRoadDesc: 'এনএইচ-১০ লাভা ডাইভাৰ্চন',
    cmdHelplinesTitle: 'হেল্পলাইন নম্বৰ',
    cmdHelplinesDesc: 'এনডিআৰএফ ১০৭৮ আৰু ১১২',
    cmdMedicalTitle: 'চিকিৎসা কনভয়',
    cmdMedicalDesc: 'অত্যাৱশ্যকীয় যোগান',
    responseSos: '🚨 জৰুৰী বিপদ সংকেত চিনাক্ত! ছাইৰেন বাজিল আৰু এনডিআৰএফ ১০৭৮ লৈ এছ.অ.এছ বাৰ্তা প্ৰেৰণ কৰা হ’ল।',
    responseShelters: '🏠 ওচৰৰ আশ্ৰয় শিবিৰ: জেএন ষ্টেডিয়াম পোল’ গ্ৰাউণ্ড (৩৪০/১২০০ ক্ষমতা)। সাহায্য সক্ৰিয়।',
    responseWeather: '🌧️ বতৰৰ সতৰ্কবাৰ্তা: মেঘালয় আৰু ছিকিমত প্ৰবল বৰষুণ অব্যাহত। ভূমিস্খলনৰ সম্ভাৱনা ৮৭%।',
    responseRoad: '🛣️ পথ জাননী: এনএইচ-১০ তিস্তা বজাৰ বন্ধ। জৰুৰী যাতায়াত লাভা বাইপাছেৰে নিয়ন্ত্ৰিত।',
    responseHelplines: '📞 জৰুৰী হেল্পলাইন: ৰাষ্ট্ৰীয় ১১২, এনডিআৰএফ ১০৭৮, ৰাজ্যিক দুৰ্যোগ নিয়ন্ত্ৰণ ১০৭০।',
    responseMedical: '🚑 চিকিৎসা কনভয়: অত্যাৱশ্যকীয় ঔষধ আৰু খাদ্য লাভা পথৰ জৰিয়তে সুকলমে পঠিওৱা হৈছে।',
    replayAudio: '🔊 পুনৰ শুনক',
    typeQuestionPlaceholder: 'প্ৰশ্ন লিখক (যেনে: আশ্ৰয় শিবিৰ, বতৰ, পথ)...',
    aiSpokenResponse: 'এআই কণ্ঠ উত্তৰ',
  },
  bn: {
    appTitle: 'লজিক্স-এনইআর',
    appSubtitle: 'এআই স্মার্ট লজিস্টিকস ও পথ গ্রিড',
    dashboard: 'ড্যাশবোর্ড',
    alerts: 'সতর্কবার্তা',
    report: 'রিপোর্ট',
    sensors: 'সেন্সর',
    settings: 'সেটিংস',
    sosEmergency: 'জরুরি এসওএস',
    signIn: 'সাইন ইন',
    signOut: 'সাইন আউট',
    emergencyContacts: 'জরুরি যোগাযোগ (পরিবার ও বন্ধু)',
    voiceMicTooltip: 'লজিক্স এআই সহায়ক',
    listeningVoice: 'ভয়েস কমান্ড শুনছে...',
    redAlert: 'রেড অ্যালার্ট - লেভেল ৪',
    evacuateNow: 'অবিলম্বে নিরাপদ স্থানে যান',
    readOfficialBulletin: 'সরকারী বুলেটিন পড়ুন',
    broadcastSMS: 'এসএমএস পাঠান 📱',
    helplines: 'জরুরি হেল্পলাইন',
    shelters: 'ত্রাণ শিবির',
    voiceAssistantTitle: 'লজিক্স এআই ভয়েস সহকারী',
    voiceAssistantSub: 'উত্তর-পূর্ব আঞ্চলিক গ্রিড',
    quickCommandsTitle: 'দ্রুত ভয়েস কমান্ড:',
    cmdSosTitle: 'জরুরি এসওএস',
    cmdSosDesc: 'সাইরেন + জিপিএস বার্তা',
    cmdSheltersTitle: 'ত্রাণ শিবির',
    cmdSheltersDesc: 'নিকটবর্তী নিরাপদ শিবির',
    cmdWeatherTitle: 'বর্ষার আবহাওয়া',
    cmdWeatherDesc: 'বৃষ্টিপাত ও মাটির আর্দ্রতা',
    cmdRoadTitle: 'সড়ক ও বাইপাস',
    cmdRoadDesc: 'এনএইচ-১০ লাভা ডাইভারশন',
    cmdHelplinesTitle: 'হেল্পলাইন নম্বর',
    cmdHelplinesDesc: 'এনডিআরএফ ১০৭৮ ও ১১২',
    cmdMedicalTitle: 'চিকিৎসা কনভয়',
    cmdMedicalDesc: 'জরুরি ওষুধ ও খাদ্য',
    responseSos: '🚨 জরুরি বিপদ সংকেত শনাক্ত! সাইরেন চালু এবং এনডিআরএফ ১০৭৮ নম্বরে জিপিএস বার্তা পাঠানো হয়েছে।',
    responseShelters: '🏠 নিকটতম ত্রাণ শিবির: জেএন স্টেডিয়াম পোলো গ্রাউন্ডস (৩৪০/১২০০ ধারণক্ষমতা)। সাহায্য সামগ্রী মজুত।',
    responseWeather: '🌧️ আবহাওয়া বার্তা: মেঘালয় ও সিকিমে ভারী বৃষ্টিপাত অব্যাহত। পাহাড় ধসের ঝুঁকি ৮৭%।',
    responseRoad: '🛣️ সড়ক পরামর্শ: এনএইচ-১০ তিস্তা বাজার অবরুদ্ধ। জরুরি গাড়ি লাভা বাইপাস দিয়ে চালানো হচ্ছে।',
    responseHelplines: '📞 জরুরি হটলাইন: জাতীয় ১১২, এনডিআরএফ ১০৭৮, রাজ্য বিপর্যয় মোকাবিলা ১০৭০।',
    responseMedical: '🚑 চিকিৎসা কনভয়: প্রয়োজনীয় ওষুধ ও ত্রাণ সামগ্রী লাভা রোড দিয়ে নিরাপদে পৌঁছানো হচ্ছে।',
    replayAudio: '🔊 পুনরায় শুনুন',
    typeQuestionPlaceholder: 'প্রশ্ন লিখুন (যেমন: ত্রাণ শিবির, আবহাওয়া, সড়ক)...',
    aiSpokenResponse: 'এআই ভয়েস উত্তর',
  },
  kha: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Route Accessibility Grid',
    dashboard: 'Dashboard',
    alerts: 'Jingma',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS JINGEH',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Lok & Kur (Emergency)',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ap ya ki bthah ktien...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Phet Shaki Shngiam Wut Wut',
    readOfficialBulletin: 'Pule Jingkyntu Sorkar',
    broadcastSMS: 'Phah SMS 📱',
    helplines: 'Helplines Jingeh',
    shelters: 'Shnong Jingshngiam',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'KI BTHAH KTIEN:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Shnong Shngiam',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Jinghap Slap',
    cmdWeatherDesc: 'Rainfall & Landslide Risk',
    cmdRoadTitle: 'Surok & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Dawai & Jingbam',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS detected! Siren ba heh ka sawa bad la phah GPS sha NDRF 1078.',
    responseShelters: '🏠 Shnong Jingshngiam: JN Stadium Polo Grounds (340/1200 Capacity). Don ki dawai bad jingbam.',
    responseWeather: '🌧️ Jinghap Slap: U slap u jur bha ha Meghalaya & Sikkim. Ka jaka ka la ktah 87%.',
    responseRoad: '🛣️ Surok NH-10: Teesta Bazaar la khang. Ki kali ki iaid lyngba ka surok Lava.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Essential Convoy: Ki dawai bad marbam la pyniaid beit lyngba ka Lava bypass.',
    replayAudio: '🔊 Sngap Biang',
    typeQuestionPlaceholder: 'Thoh jingkylli (Shnong Shngiam, Slap, Surok)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  gar: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Smart Logistics Grid',
    dashboard: 'Dashboard',
    alerts: 'Mikrakani',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS KENANI',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Ma·drang & Ripel (Emergency)',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ku·rang knaenga...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Re·angbo Shngiamchi Wut Wut',
    readOfficialBulletin: 'Poraibo Nokgipa Sea',
    broadcastSMS: 'Watbo SMS 📱',
    helplines: 'Helplines Dakchakan',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'KU·RANG BTHAH:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Mikka Waani',
    cmdWeatherDesc: 'Rainfall & Hazard Risk',
    cmdRoadTitle: 'Rama & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Sam & Chaani',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS detected! Siren gam·ataha aro GPS-ko NDRF 1078-ona watataha.',
    responseShelters: '🏠 Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Chaani aro sam donga.',
    responseWeather: '🌧️ Mikka Waani: Meghalaya aro Sikkim-o mikka jame waaenga. A·solani 87% donga.',
    responseRoad: '🛣️ Rama Advisory: NH-10 Teesta Bazaar champenga. Gari Lava bypass rama gita re·enga.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Essential Convoy: Sam aro cha·anirangko Lava rama gita sorkari watatenga.',
    replayAudio: '🔊 Knapil·tai',
    typeQuestionPlaceholder: 'Segibo sing·ani (Relief Camp, Mikka, Rama)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  mni: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Accessibility Grid',
    dashboard: 'ꯗꯦꯁꯕꯣꯔꯗ',
    alerts: 'ꯆꯦꯛꯁꯤꯟꯋꯥ',
    report: 'ꯔꯤꯄꯣꯔꯠ',
    sensors: 'ꯁꯦꯟꯁꯔ',
    settings: 'ꯁꯦꯇꯤꯡꯁ',
    sosEmergency: 'ꯑꯀꯅꯕ ꯑꯦꯁ.ꯑꯣ.ꯑꯦꯁ',
    signIn: 'ꯁꯥꯏꯟ ꯏꯟ',
    signOut: 'ꯁꯥꯏꯟ ꯑꯥꯎꯠ',
    emergencyContacts: 'ꯏꯃꯨꯡ-ꯃꯅꯨꯡ (Emergency)',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'ꯈꯣꯟꯊꯣꯛ ꯇꯥꯕ꯭ꯔꯤ...',
    redAlert: 'ꯔꯦꯗ ꯑꯦꯂꯥꯔꯠ - ꯂꯦꯕꯦꯜ ꯴',
    evacuateNow: 'ꯊꯨꯅꯥ ꯅꯥꯅꯕ ꯃꯐꯝꯗ ꯆꯠꯂꯨ',
    readOfficialBulletin: 'ꯑꯣꯐꯤꯁꯤꯑꯦꯜ Bulletin ꯄꯥꯕꯤꯌꯨ',
    broadcastSMS: 'SMS ꯊꯥꯕꯤꯌꯨ 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'ꯅꯣꯡ ꯆꯨꯕ',
    cmdWeatherDesc: 'Rainfall & Saturation',
    cmdRoadTitle: 'ꯂꯝꯕꯤ & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helplines',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS Detected! Siren activate toure amasung GPS location NDRF 1078 da thakhre.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Hidag amasung chinjak leiri.',
    responseWeather: '🌧️ Weather Advisory: Meghalaya amasung Sikkim da akanba nong churi. Chingrum tubagi risk 87% leiri.',
    responseRoad: '🛣️ Route Advisory: NH-10 Teesta Bazaar thingjinre. Emergency gari Lava bypass lamda chatli.',
    responseHelplines: '📞 Emergency Helplines: National 112, NDRF 1078, State Control 1070.',
    responseMedical: '🚑 Essential Convoy: Hidag amasung ration Lava lamda safe oina pukhre.',
    replayAudio: '🔊 ꯑꯃꯨꯛ ꯇꯥꯕꯤꯌꯨ',
    typeQuestionPlaceholder: 'Wahang Iyu (Shelters, Weather, Lambi)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  mzo: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Transport Grid',
    dashboard: 'Dashboard',
    alerts: 'Vantlang Warning',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS HLAMAU',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Chhungkua & Thiante (Emergency)',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Ngaihthlak lai...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Insawn nghal rawh',
    readOfficialBulletin: 'Chhiar Rawh Bulletin',
    broadcastSMS: 'Thawn Rawh SMS 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX Voice AI Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Ruah Sur Dan',
    cmdWeatherDesc: 'Rainfall & Hazard',
    cmdRoadTitle: 'Kawng & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Damdawi & Chaw',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency SOS hmuh a ni! Siren a ri a, GPS SOS chu NDRF 1078-ah thawn nghal a ni.',
    responseShelters: '🏠 Hnaivai ber Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Damdawi leh ei tur a awm.',
    responseWeather: '🌧️ Khawchin: Meghalaya leh Sikkim-ah ruah nasa takin a sur a. Lei min theihna 87% a tling.',
    responseRoad: '🛣️ Kawng Chanchin: NH-10 Teesta Bazaar a ping a. Emergency motor chu Lava kawngah kualtir a ni.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Damdawi Convoy: Damdawi leh chaw chu Lava kawngah him takin thawn a ni.',
    replayAudio: '🔊 Ngaithla Nawn Rawh',
    typeQuestionPlaceholder: 'Zawhna ziak rawh (Shelters, Ruah, Kawng)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  nag: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Accessibility Grid',
    dashboard: 'Dashboard',
    alerts: 'Warning Alerts',
    report: 'Report Alert',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS EMERGENCY',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Emergency Contacts',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Listening for command...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Move to safe place immediately',
    readOfficialBulletin: 'Read Official Bulletin',
    broadcastSMS: 'Broadcast via SMS 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX AI Voice Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Nearest Safe Camps',
    cmdWeatherTitle: 'Monsoon Weather',
    cmdWeatherDesc: 'Rainfall & Landslide',
    cmdRoadTitle: 'Road & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helplines',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supply Grid',
    responseSos: '🚨 Emergency danger detected! Siren started and GPS SOS sent to NDRF 1078.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Food and medicines ready.',
    responseWeather: '🌧️ Weather Alert: Heavy rain continuing across Meghalaya and Sikkim. Landslide risk is 87%.',
    responseRoad: '🛣️ Road Status: NH-10 Teesta Bazaar is blocked. Convoys diverted via Lava bypass.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Medical Supply: Essential medicine convoys cleared through Lava bypass road.',
    replayAudio: '🔊 Replay Audio',
    typeQuestionPlaceholder: 'Type a question (Shelters, Weather, Road)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  kok: {
    appTitle: 'LOGIX-NER',
    appSubtitle: 'AI Logistics & Route Grid',
    dashboard: 'Dashboard',
    alerts: 'Warning',
    report: 'Report',
    sensors: 'Sensors',
    settings: 'Settings',
    sosEmergency: 'SOS DANGER',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    emergencyContacts: 'Lok & Nogor (Emergency)',
    voiceMicTooltip: 'LOGIX AI Assistant',
    listeningVoice: 'Khorang Khnagjakphai...',
    redAlert: 'RED ALERT - LEVEL 4',
    evacuateNow: 'Thangbo Safe Place-o',
    readOfficialBulletin: 'Read Official Bulletin',
    broadcastSMS: 'Send SMS 📱',
    helplines: 'Emergency Helplines',
    shelters: 'Relief Camps',
    voiceAssistantTitle: 'LOGIX AI Voice Assistant',
    voiceAssistantSub: 'Seven Sisters Regional Grid',
    quickCommandsTitle: 'QUICK VOICE COMMANDS:',
    cmdSosTitle: 'Emergency SOS',
    cmdSosDesc: 'Siren + GPS Broadcast',
    cmdSheltersTitle: 'Relief Shelters',
    cmdSheltersDesc: 'Safe Relief Camps',
    cmdWeatherTitle: 'Noh Watnai',
    cmdWeatherDesc: 'Rainfall & Saturation',
    cmdRoadTitle: 'Lama & Bypass',
    cmdRoadDesc: 'NH-10 Lava Diversion',
    cmdHelplinesTitle: 'Helpline Number',
    cmdHelplinesDesc: 'NDRF 1078 & 112',
    cmdMedicalTitle: 'Medical Convoys',
    cmdMedicalDesc: 'Essential Supplies',
    responseSos: '🚨 Emergency SOS detected! Siren rwjakha tei GPS SOS NDRF 1078-o thangkha.',
    responseShelters: '🏠 Nearest Relief Camp: JN Stadium Polo Grounds (340/1200 Capacity). Sam tei chakhwtal tongo.',
    responseWeather: '🌧️ Noh Watnai: Meghalaya tei Sikkim-o nokha kwbang watlai tongo. Hazard risk 87%.',
    responseRoad: '🛣️ Lama Advisory: NH-10 Teesta Bazaar borkha. Garirok Lava bypass lama bai thango.',
    responseHelplines: '📞 Helplines: National 112, NDRF 1078, State Disaster 1070.',
    responseMedical: '🚑 Medical Supply: Essential sam tei ration Lava lama bai safe-o thangkha.',
    replayAudio: '🔊 Khorang Khnabil',
    typeQuestionPlaceholder: 'Songjakbai sei (Shelters, Noh, Lama)...',
    aiSpokenResponse: 'AI Spoken Response',
  },
  ne: {
    appTitle: 'लॉजिक्स-एनईआर',
    appSubtitle: 'एआई आपूर्ति र मार्ग सुगमयता ग्रिड',
    dashboard: 'ड्यासबोर्ड',
    alerts: 'चेतावनीहरू',
    report: 'रिपोर्ट पठाउनुहोस्',
    sensors: 'सेन्सर डाटा',
    settings: 'सेटिङ्हरू',
    sosEmergency: 'आपत्कालीन एसओएस',
    signIn: 'साइन इन गर्नुहोस्',
    signOut: 'साइन आउट',
    emergencyContacts: 'आपत्कालीन सम्पर्कहरू (परिवार र साथीहरू)',
    voiceMicTooltip: 'लॉजिक्स एआई सहायक',
    listeningVoice: 'आवाज आदेश सुन्दैछ...',
    redAlert: 'रेड अलर्ट - स्तर ४',
    evacuateNow: 'तुरुन्तै सुरक्षित स्थानमा जानुहोस्',
    readOfficialBulletin: 'आधिकारिक समाचार पढ्नुहोस्',
    broadcastSMS: 'एसएमएस पठाउनुहोस् 📱',
    helplines: 'आपत्कालीन हेल्पलाइनहरू',
    shelters: 'राहत शिविरहरू',
    voiceAssistantTitle: 'लॉजिक्स एआई भ्वाइस सहायक',
    voiceAssistantSub: 'उत्तर-पूर्व क्षेत्रीय ग्रिड',
    quickCommandsTitle: 'द्रुत भ्वाइस कमान्डहरू:',
    cmdSosTitle: 'आपत्कालीन एसओएस',
    cmdSosDesc: 'साइरन + जीपीएस सन्देश',
    cmdSheltersTitle: 'राहत शिविरहरू',
    cmdSheltersDesc: 'नजिकको सुरक्षित शिविर',
    cmdWeatherTitle: 'मनसुन मौसम',
    cmdWeatherDesc: 'वर्षा र पहिरो जोखिम',
    cmdRoadTitle: 'सडक र बाइपास',
    cmdRoadDesc: 'एनएच-१० लाभा मार्ग',
    cmdHelplinesTitle: 'हेल्पलाइन नम्बरहरू',
    cmdHelplinesDesc: 'एनडीआरएफ १०७८ र ११२',
    cmdMedicalTitle: 'चिकित्सा आपूर्ति',
    cmdMedicalDesc: 'अत्यावश्यक राहत सामग्री',
    responseSos: '🚨 आपत्कालीन जोखिम पत्ता लाग्यो! साइरन बज्यो र एनडीआरएफ १०७८ मा जीपीएस स्थान पठाइयो।',
    responseShelters: '🏠 नजिकको राहत शिविर: जेएन स्टेडियम पोलो ग्राउन्ड्स (३४०/१२०० क्षमता)। खाना र औषधि उपलब्ध छ।',
    responseWeather: '🌧️ मौसम सल्लाह: मेघालय र सिक्किममा भारी मनसुनी वर्षा जारी छ। पहिरो जोखिम ८७% छ।',
    responseRoad: '🛣️ सडक सल्लाह: एनएच-१० टिस्टा बजार अवरुद्ध छ। आपत्कालीन गाडीहरू लाभा बाइपासबाट पठाइएको छ।',
    responseHelplines: '📞 आपत्कालीन हेल्पलाइनहरू: राष्ट्रिय ११२, एनडीआरएफ १०७८, राज्य विपद् नियन्त्रण १०७०।',
    responseMedical: '🚑 चिकित्सा आपूर्ति: आवश्यक औषधि र राशन लाभा बाइपास मार्गबाट सुरक्षित पठाइएको छ।',
    replayAudio: '🔊 फेरि सुन्नुहोस्',
    typeQuestionPlaceholder: 'प्रश्न लेख्नुहोस् (जस्तै: राहत शिविर, मौसम, सडक)...',
    aiSpokenResponse: 'एआई भ्वाइस जवाफ',
  },
};

const LANGUAGE_KEY = 'logix_selected_language_v1';
let currentLang: LanguageCode = 'en';

export function getSelectedLanguage(): LanguageCode {
  if (typeof window === 'undefined' || !window.localStorage) return currentLang;
  try {
    const saved = window.localStorage.getItem(LANGUAGE_KEY) as LanguageCode;
    if (saved && TRANSLATIONS[saved]) {
      currentLang = saved;
      return saved;
    }
  } catch {}
  return 'en';
}

export function setSelectedLanguage(lang: LanguageCode): void {
  currentLang = lang;
  if (typeof window === 'undefined' || !window.localStorage) return;
  try {
    window.localStorage.setItem(LANGUAGE_KEY, lang);
  } catch {}
}

export function getTranslations(lang: LanguageCode = getSelectedLanguage()): TranslationDictionary {
  return TRANSLATIONS[lang] || TRANSLATIONS['en'];
}
